// 由 scripts/gen-vocab.mjs 從 content/vocab.v1.csv 與 content/examples.v1.tsv 產生，不要手動編輯。
// 改題庫請改 CSV／TSV，然後跑 pnpm gen:vocab。

import type { VocabEntry, VocabExample } from './static-provider';

export const VOCAB_SOURCE = 'content/vocab.v1.csv';

export const VOCAB: readonly VocabEntry[] = [
  { id: 'v0001', en: 'say', zh: '說', level: 1, source: 'ecdict-v1' },
  { id: 'v0002', en: 'get', zh: '得到', level: 1, source: 'ecdict-v1' },
  { id: 'v0003', en: 'make', zh: '製造', level: 1, source: 'ecdict-v1' },
  { id: 'v0004', en: 'know', zh: '知道', level: 1, source: 'ecdict-v1' },
  { id: 'v0005', en: 'one', zh: '一', level: 1, source: 'ecdict-v1' },
  { id: 'v0006', en: 'time', zh: '時間', level: 1, source: 'ecdict-v1' },
  { id: 'v0007', en: 'year', zh: '年', level: 1, source: 'ecdict-v1' },
  { id: 'v0008', en: 'think', zh: '想', level: 1, source: 'ecdict-v1' },
  { id: 'v0009', en: 'people', zh: '人', level: 1, source: 'ecdict-v1' },
  { id: 'v0010', en: 'take', zh: '拿', level: 1, source: 'ecdict-v1' },
  { id: 'v0011', en: 'see', zh: '看見', level: 1, source: 'ecdict-v1' },
  { id: 'v0012', en: 'come', zh: '過來', level: 1, source: 'ecdict-v1' },
  { id: 'v0013', en: 'now', zh: '現在', level: 1, source: 'ecdict-v1' },
  { id: 'v0014', en: 'like', zh: '相似的', level: 1, source: 'ecdict-v1' },
  { id: 'v0015', en: 'two', zh: '二', level: 1, source: 'ecdict-v1' },
  { id: 'v0016', en: 'more', zh: '更多', level: 1, source: 'ecdict-v1' },
  { id: 'v0017', en: 'want', zh: '需要的東西', level: 1, source: 'ecdict-v1' },
  { id: 'v0018', en: 'way', zh: '路', level: 1, source: 'ecdict-v1' },
  { id: 'v0019', en: 'look', zh: '一看', level: 1, source: 'ecdict-v1' },
  { id: 'v0020', en: 'first', zh: '首先', level: 1, source: 'ecdict-v1' },
  { id: 'v0021', en: 'new', zh: '新的', level: 1, source: 'ecdict-v1' },
  { id: 'v0022', en: 'day', zh: '天', level: 1, source: 'ecdict-v1' },
  { id: 'v0023', en: 'use', zh: '使用', level: 1, source: 'ecdict-v1' },
  { id: 'v0024', en: 'man', zh: '男人', level: 1, source: 'ecdict-v1' },
  { id: 'v0025', en: 'find', zh: '發現', level: 1, source: 'ecdict-v1' },
  { id: 'v0026', en: 'thing', zh: '事物', level: 1, source: 'ecdict-v1' },
  { id: 'v0027', en: 'give', zh: '彈性', level: 1, source: 'ecdict-v1' },
  { id: 'v0028', en: 'many', zh: '多數', level: 1, source: 'ecdict-v1' },
  { id: 'v0029', en: 'well', zh: '井', level: 1, source: 'ecdict-v1' },
  { id: 'v0030', en: 'tell', zh: '告訴', level: 1, source: 'ecdict-v1' },
  { id: 'v0031', en: 'back', zh: '後面的', level: 1, source: 'ecdict-v1' },
  { id: 'v0032', en: 'good', zh: '善行', level: 1, source: 'ecdict-v1' },
  { id: 'v0033', en: 'woman', zh: '女人', level: 1, source: 'ecdict-v1' },
  { id: 'v0034', en: 'life', zh: '生活', level: 1, source: 'ecdict-v1' },
  { id: 'v0035', en: 'child', zh: '孩子', level: 1, source: 'ecdict-v1' },
  { id: 'v0036', en: 'work', zh: '工作', level: 1, source: 'ecdict-v1' },
  { id: 'v0037', en: 'call', zh: '呼叫', level: 1, source: 'ecdict-v1' },
  { id: 'v0038', en: 'world', zh: '世界', level: 1, source: 'ecdict-v1' },
  { id: 'v0039', en: 'school', zh: '學校', level: 1, source: 'ecdict-v1' },
  { id: 'v0040', en: 'try', zh: '嘗試', level: 1, source: 'ecdict-v1' },
  { id: 'v0041', en: 'last', zh: '最後的', level: 1, source: 'ecdict-v1' },
  { id: 'v0042', en: 'ask', zh: '問', level: 1, source: 'ecdict-v1' },
  { id: 'v0043', en: 'need', zh: '需要', level: 1, source: 'ecdict-v1' },
  { id: 'v0044', en: 'feel', zh: '感覺', level: 1, source: 'ecdict-v1' },
  { id: 'v0045', en: 'three', zh: '三', level: 1, source: 'ecdict-v1' },
  { id: 'v0046', en: 'state', zh: '州', level: 1, source: 'ecdict-v1' },
  { id: 'v0047', en: 'never', zh: '從不', level: 1, source: 'ecdict-v1' },
  { id: 'v0048', en: 'become', zh: '變成', level: 1, source: 'ecdict-v1' },
  { id: 'v0049', en: 'high', zh: '高度', level: 1, source: 'ecdict-v1' },
  { id: 'v0050', en: 'something', zh: '某事', level: 1, source: 'ecdict-v1' },
  { id: 'v0051', en: 'really', zh: '實際上', level: 1, source: 'ecdict-v1' },
  { id: 'v0052', en: 'most', zh: '最多', level: 1, source: 'ecdict-v1' },
  { id: 'v0053', en: 'another', zh: '另外的', level: 1, source: 'ecdict-v1' },
  { id: 'v0054', en: 'much', zh: '大量', level: 1, source: 'ecdict-v1' },
  { id: 'v0055', en: 'family', zh: '家庭', level: 1, source: 'ecdict-v1' },
  { id: 'v0056', en: 'own', zh: '自己的', level: 1, source: 'ecdict-v1' },
  { id: 'v0057', en: 'leave', zh: '許可', level: 1, source: 'ecdict-v1' },
  { id: 'v0058', en: 'put', zh: '放', level: 1, source: 'ecdict-v1' },
  { id: 'v0059', en: 'old', zh: '以前', level: 1, source: 'ecdict-v1' },
  { id: 'v0060', en: 'mean', zh: '低劣的', level: 1, source: 'ecdict-v1' },
  { id: 'v0061', en: 'keep', zh: '生計', level: 1, source: 'ecdict-v1' },
  { id: 'v0062', en: 'student', zh: '學生', level: 1, source: 'ecdict-v1' },
  { id: 'v0063', en: 'let', zh: '讓', level: 1, source: 'ecdict-v1' },
  { id: 'v0064', en: 'great', zh: '大的', level: 1, source: 'ecdict-v1' },
  { id: 'v0065', en: 'same', zh: '相同的', level: 1, source: 'ecdict-v1' },
  { id: 'v0066', en: 'group', zh: '團體', level: 1, source: 'ecdict-v1' },
  { id: 'v0067', en: 'begin', zh: '開始', level: 1, source: 'ecdict-v1' },
  { id: 'v0068', en: 'seem', zh: '象是', level: 1, source: 'ecdict-v1' },
  { id: 'v0069', en: 'country', zh: '國家', level: 1, source: 'ecdict-v1' },
  { id: 'v0070', en: 'help', zh: '幫忙', level: 1, source: 'ecdict-v1' },
  { id: 'v0071', en: 'talk', zh: '談話', level: 1, source: 'ecdict-v1' },
  { id: 'v0072', en: 'turn', zh: '轉彎', level: 1, source: 'ecdict-v1' },
  { id: 'v0073', en: 'problem', zh: '問題', level: 1, source: 'ecdict-v1' },
  { id: 'v0074', en: 'start', zh: '驚起', level: 1, source: 'ecdict-v1' },
  { id: 'v0075', en: 'hand', zh: '手', level: 1, source: 'ecdict-v1' },
  { id: 'v0076', en: 'show', zh: '顯示', level: 1, source: 'ecdict-v1' },
  { id: 'v0077', en: 'part', zh: '部分', level: 1, source: 'ecdict-v1' },
  { id: 'v0078', en: 'place', zh: '地方', level: 1, source: 'ecdict-v1' },
  { id: 'v0079', en: 'few', zh: '很少的', level: 1, source: 'ecdict-v1' },
  { id: 'v0080', en: 'case', zh: '情形', level: 1, source: 'ecdict-v1' },
  { id: 'v0081', en: 'week', zh: '星期', level: 1, source: 'ecdict-v1' },
  { id: 'v0082', en: 'company', zh: '公司', level: 1, source: 'ecdict-v1' },
  { id: 'v0083', en: 'system', zh: '系統', level: 1, source: 'ecdict-v1' },
  { id: 'v0084', en: 'right', zh: '權利', level: 1, source: 'ecdict-v1' },
  { id: 'v0085', en: 'program', zh: '節目', level: 1, source: 'ecdict-v1' },
  { id: 'v0086', en: 'hear', zh: '聽到', level: 1, source: 'ecdict-v1' },
  { id: 'v0087', en: 'play', zh: '遊戲', level: 1, source: 'ecdict-v1' },
  { id: 'v0088', en: 'government', zh: '政府', level: 1, source: 'ecdict-v1' },
  { id: 'v0089', en: 'run', zh: '跑', level: 1, source: 'ecdict-v1' },
  { id: 'v0090', en: 'small', zh: '小的', level: 1, source: 'ecdict-v1' },
  { id: 'v0091', en: 'number', zh: '數', level: 1, source: 'ecdict-v1' },
  { id: 'v0092', en: 'always', zh: '總是', level: 1, source: 'ecdict-v1' },
  { id: 'v0093', en: 'move', zh: '移動', level: 1, source: 'ecdict-v1' },
  { id: 'v0094', en: 'night', zh: '夜', level: 1, source: 'ecdict-v1' },
  { id: 'v0095', en: 'live', zh: '活的', level: 1, source: 'ecdict-v1' },
  { id: 'v0096', en: 'point', zh: '點', level: 1, source: 'ecdict-v1' },
  { id: 'v0097', en: 'believe', zh: '相信', level: 1, source: 'ecdict-v1' },
  { id: 'v0098', en: 'hold', zh: '把握', level: 1, source: 'ecdict-v1' },
  { id: 'v0099', en: 'today', zh: '今天', level: 1, source: 'ecdict-v1' },
  { id: 'v0100', en: 'bring', zh: '帶來', level: 1, source: 'ecdict-v1' },
  { id: 'v0101', en: 'happen', zh: '發生', level: 1, source: 'ecdict-v1' },
  { id: 'v0102', en: 'next', zh: '下一個', level: 1, source: 'ecdict-v1' },
  { id: 'v0103', en: 'million', zh: '百萬', level: 1, source: 'ecdict-v1' },
  { id: 'v0104', en: 'home', zh: '家', level: 1, source: 'ecdict-v1' },
  { id: 'v0105', en: 'water', zh: '水', level: 1, source: 'ecdict-v1' },
  { id: 'v0106', en: 'room', zh: '房間', level: 1, source: 'ecdict-v1' },
  { id: 'v0107', en: 'write', zh: '書寫', level: 1, source: 'ecdict-v1' },
  { id: 'v0108', en: 'mother', zh: '母親', level: 1, source: 'ecdict-v1' },
  { id: 'v0109', en: 'area', zh: '區域', level: 1, source: 'ecdict-v1' },
  { id: 'v0110', en: 'national', zh: '國家的', level: 1, source: 'ecdict-v1' },
  { id: 'v0111', en: 'money', zh: '金錢', level: 1, source: 'ecdict-v1' },
  { id: 'v0112', en: 'story', zh: '故事', level: 1, source: 'ecdict-v1' },
  { id: 'v0113', en: 'young', zh: '年輕的', level: 1, source: 'ecdict-v1' },
  { id: 'v0114', en: 'fact', zh: '事實', level: 1, source: 'ecdict-v1' },
  { id: 'v0115', en: 'month', zh: '月', level: 1, source: 'ecdict-v1' },
  { id: 'v0116', en: 'different', zh: '不同的', level: 1, source: 'ecdict-v1' },
  { id: 'v0117', en: 'lot', zh: '運氣', level: 1, source: 'ecdict-v1' },
  { id: 'v0118', en: 'study', zh: '學習', level: 1, source: 'ecdict-v1' },
  { id: 'v0119', en: 'book', zh: '書', level: 1, source: 'ecdict-v1' },
  { id: 'v0120', en: 'eye', zh: '眼睛', level: 1, source: 'ecdict-v1' },
  { id: 'v0121', en: 'word', zh: '話', level: 1, source: 'ecdict-v1' },
  { id: 'v0122', en: 'business', zh: '生意', level: 1, source: 'ecdict-v1' },
  { id: 'v0123', en: 'four', zh: '四', level: 1, source: 'ecdict-v1' },
  { id: 'v0124', en: 'issue', zh: '發行', level: 1, source: 'ecdict-v1' },
  { id: 'v0125', en: 'side', zh: '旁邊', level: 1, source: 'ecdict-v1' },
  { id: 'v0126', en: 'kind', zh: '種類', level: 1, source: 'ecdict-v1' },
  { id: 'v0127', en: 'head', zh: '頭', level: 1, source: 'ecdict-v1' },
  { id: 'v0128', en: 'far', zh: '遠的', level: 1, source: 'ecdict-v1' },
  { id: 'v0129', en: 'black', zh: '黑色', level: 1, source: 'ecdict-v1' },
  { id: 'v0130', en: 'long', zh: '長的', level: 1, source: 'ecdict-v1' },
  { id: 'v0131', en: 'little', zh: '一點點', level: 1, source: 'ecdict-v1' },
  { id: 'v0132', en: 'house', zh: '房子', level: 1, source: 'ecdict-v1' },
  { id: 'v0133', en: 'provide', zh: '提供', level: 1, source: 'ecdict-v1' },
  { id: 'v0134', en: 'service', zh: '服務', level: 1, source: 'ecdict-v1' },
  { id: 'v0135', en: 'friend', zh: '朋友', level: 1, source: 'ecdict-v1' },
  { id: 'v0136', en: 'important', zh: '重要的', level: 1, source: 'ecdict-v1' },
  { id: 'v0137', en: 'father', zh: '父親', level: 1, source: 'ecdict-v1' },
  { id: 'v0138', en: 'sit', zh: '坐', level: 1, source: 'ecdict-v1' },
  { id: 'v0139', en: 'away', zh: '離去', level: 1, source: 'ecdict-v1' },
  { id: 'v0140', en: 'power', zh: '力', level: 1, source: 'ecdict-v1' },
  { id: 'v0141', en: 'hour', zh: '小時', level: 1, source: 'ecdict-v1' },
  { id: 'v0142', en: 'game', zh: '比賽', level: 1, source: 'ecdict-v1' },
  { id: 'v0143', en: 'often', zh: '時常', level: 1, source: 'ecdict-v1' },
  { id: 'v0144', en: 'line', zh: '列', level: 1, source: 'ecdict-v1' },
  { id: 'v0145', en: 'political', zh: '政治的', level: 1, source: 'ecdict-v1' },
  { id: 'v0146', en: 'end', zh: '結束', level: 1, source: 'ecdict-v1' },
  { id: 'v0147', en: 'ever', zh: '曾經', level: 1, source: 'ecdict-v1' },
  { id: 'v0148', en: 'stand', zh: '站立', level: 1, source: 'ecdict-v1' },
  { id: 'v0149', en: 'bad', zh: '壞的', level: 1, source: 'ecdict-v1' },
  { id: 'v0150', en: 'lose', zh: '遺失', level: 1, source: 'ecdict-v1' },
  { id: 'v0151', en: 'however', zh: '然而', level: 1, source: 'ecdict-v1' },
  { id: 'v0152', en: 'member', zh: '成員', level: 1, source: 'ecdict-v1' },
  { id: 'v0153', en: 'pay', zh: '薪資', level: 1, source: 'ecdict-v1' },
  { id: 'v0154', en: 'law', zh: '法律', level: 1, source: 'ecdict-v1' },
  { id: 'v0155', en: 'meet', zh: '會', level: 1, source: 'ecdict-v1' },
  { id: 'v0156', en: 'car', zh: '汽車', level: 1, source: 'ecdict-v1' },
  { id: 'v0157', en: 'city', zh: '城市', level: 1, source: 'ecdict-v1' },
  { id: 'v0158', en: 'almost', zh: '幾乎', level: 1, source: 'ecdict-v1' },
  { id: 'v0159', en: 'include', zh: '包括', level: 1, source: 'ecdict-v1' },
  { id: 'v0160', en: 'continue', zh: '繼續', level: 1, source: 'ecdict-v1' },
  { id: 'v0161', en: 'set', zh: '日落', level: 1, source: 'ecdict-v1' },
  { id: 'v0162', en: 'later', zh: '以後', level: 1, source: 'ecdict-v1' },
  { id: 'v0163', en: 'community', zh: '社群', level: 1, source: 'ecdict-v1' },
  { id: 'v0164', en: 'name', zh: '名字', level: 1, source: 'ecdict-v1' },
  { id: 'v0165', en: 'five', zh: '五', level: 1, source: 'ecdict-v1' },
  { id: 'v0166', en: 'once', zh: '一次', level: 1, source: 'ecdict-v1' },
  { id: 'v0167', en: 'white', zh: '白色', level: 1, source: 'ecdict-v1' },
  { id: 'v0168', en: 'least', zh: '最少', level: 1, source: 'ecdict-v1' },
  { id: 'v0169', en: 'president', zh: '總統', level: 1, source: 'ecdict-v1' },
  { id: 'v0170', en: 'real', zh: '真的', level: 1, source: 'ecdict-v1' },
  { id: 'v0171', en: 'change', zh: '變化', level: 1, source: 'ecdict-v1' },
  { id: 'v0172', en: 'team', zh: '隊', level: 1, source: 'ecdict-v1' },
  { id: 'v0173', en: 'minute', zh: '分', level: 1, source: 'ecdict-v1' },
  { id: 'v0174', en: 'best', zh: '最好的', level: 1, source: 'ecdict-v1' },
  { id: 'v0175', en: 'several', zh: '幾個的', level: 1, source: 'ecdict-v1' },
  { id: 'v0176', en: 'idea', zh: '主意', level: 1, source: 'ecdict-v1' },
  { id: 'v0177', en: 'kid', zh: '小山羊', level: 1, source: 'ecdict-v1' },
  { id: 'v0178', en: 'body', zh: '身體', level: 1, source: 'ecdict-v1' },
  { id: 'v0179', en: 'information', zh: '訊息', level: 1, source: 'ecdict-v1' },
  { id: 'v0180', en: 'nothing', zh: '無', level: 1, source: 'ecdict-v1' },
  { id: 'v0181', en: 'lead', zh: '鉛', level: 1, source: 'ecdict-v1' },
  { id: 'v0182', en: 'social', zh: '社會的', level: 1, source: 'ecdict-v1' },
  { id: 'v0183', en: 'understand', zh: '理解', level: 1, source: 'ecdict-v1' },
  { id: 'v0184', en: 'watch', zh: '觀察', level: 1, source: 'ecdict-v1' },
  { id: 'v0185', en: 'together', zh: '一起', level: 1, source: 'ecdict-v1' },
  { id: 'v0186', en: 'follow', zh: '跟隨', level: 1, source: 'ecdict-v1' },
  { id: 'v0187', en: 'parent', zh: '父母', level: 1, source: 'ecdict-v1' },
  { id: 'v0188', en: 'stop', zh: '停止', level: 1, source: 'ecdict-v1' },
  { id: 'v0189', en: 'face', zh: '臉', level: 1, source: 'ecdict-v1' },
  { id: 'v0190', en: 'anything', zh: '任何事', level: 1, source: 'ecdict-v1' },
  { id: 'v0191', en: 'create', zh: '創造', level: 1, source: 'ecdict-v1' },
  { id: 'v0192', en: 'public', zh: '公眾', level: 1, source: 'ecdict-v1' },
  { id: 'v0193', en: 'already', zh: '已經', level: 1, source: 'ecdict-v1' },
  { id: 'v0194', en: 'read', zh: '讀', level: 1, source: 'ecdict-v1' },
  { id: 'v0195', en: 'level', zh: '水平', level: 1, source: 'ecdict-v1' },
  { id: 'v0196', en: 'allow', zh: '允許', level: 1, source: 'ecdict-v1' },
  { id: 'v0197', en: 'add', zh: '增加', level: 1, source: 'ecdict-v1' },
  { id: 'v0198', en: 'office', zh: '辦公室', level: 1, source: 'ecdict-v1' },
  { id: 'v0199', en: 'spend', zh: '花費', level: 1, source: 'ecdict-v1' },
  { id: 'v0200', en: 'door', zh: '門', level: 1, source: 'ecdict-v1' },
  { id: 'v0201', en: 'health', zh: '健康', level: 1, source: 'ecdict-v1' },
  { id: 'v0202', en: 'art', zh: '藝術', level: 1, source: 'ecdict-v1' },
  { id: 'v0203', en: 'sure', zh: '確信', level: 1, source: 'ecdict-v1' },
  { id: 'v0204', en: 'war', zh: '戰爭', level: 1, source: 'ecdict-v1' },
  { id: 'v0205', en: 'history', zh: '歷史', level: 1, source: 'ecdict-v1' },
  { id: 'v0206', en: 'party', zh: '宴會', level: 1, source: 'ecdict-v1' },
  { id: 'v0207', en: 'grow', zh: '種植', level: 1, source: 'ecdict-v1' },
  { id: 'v0208', en: 'result', zh: '結果', level: 1, source: 'ecdict-v1' },
  { id: 'v0209', en: 'open', zh: '公開', level: 1, source: 'ecdict-v1' },
  { id: 'v0210', en: 'morning', zh: '早晨', level: 1, source: 'ecdict-v1' },
  { id: 'v0211', en: 'walk', zh: '走', level: 1, source: 'ecdict-v1' },
  { id: 'v0212', en: 'reason', zh: '理由', level: 1, source: 'ecdict-v1' },
  { id: 'v0213', en: 'low', zh: '低點', level: 1, source: 'ecdict-v1' },
  { id: 'v0214', en: 'win', zh: '贏得', level: 1, source: 'ecdict-v1' },
  { id: 'v0215', en: 'research', zh: '研究', level: 1, source: 'ecdict-v1' },
  { id: 'v0216', en: 'girl', zh: '女孩', level: 1, source: 'ecdict-v1' },
  { id: 'v0217', en: 'guy', zh: '傢伙', level: 1, source: 'ecdict-v1' },
  { id: 'v0218', en: 'early', zh: '早的', level: 1, source: 'ecdict-v1' },
  { id: 'v0219', en: 'food', zh: '食物', level: 1, source: 'ecdict-v1' },
  { id: 'v0220', en: 'moment', zh: '片刻', level: 1, source: 'ecdict-v1' },
  { id: 'v0221', en: 'air', zh: '空氣', level: 1, source: 'ecdict-v1' },
  { id: 'v0222', en: 'teacher', zh: '教師', level: 1, source: 'ecdict-v1' },
  { id: 'v0223', en: 'force', zh: '力量', level: 1, source: 'ecdict-v1' },
  { id: 'v0224', en: 'offer', zh: '給予', level: 1, source: 'ecdict-v1' },
  { id: 'v0225', en: 'enough', zh: '充足', level: 1, source: 'ecdict-v1' },
  { id: 'v0226', en: 'education', zh: '教育', level: 1, source: 'ecdict-v1' },
  { id: 'v0227', en: 'remember', zh: '記得', level: 1, source: 'ecdict-v1' },
  { id: 'v0228', en: 'foot', zh: '腳', level: 1, source: 'ecdict-v1' },
  { id: 'v0229', en: 'second', zh: '秒', level: 1, source: 'ecdict-v1' },
  { id: 'v0230', en: 'boy', zh: '男孩', level: 1, source: 'ecdict-v1' },
  { id: 'v0231', en: 'maybe', zh: '也許', level: 1, source: 'ecdict-v1' },
  { id: 'v0232', en: 'able', zh: '能幹的', level: 1, source: 'ecdict-v1' },
  { id: 'v0233', en: 'age', zh: '年齡', level: 1, source: 'ecdict-v1' },
  { id: 'v0234', en: 'policy', zh: '政策', level: 1, source: 'ecdict-v1' },
  { id: 'v0235', en: 'everything', zh: '每件事物', level: 1, source: 'ecdict-v1' },
  { id: 'v0236', en: 'love', zh: '愛', level: 1, source: 'ecdict-v1' },
  { id: 'v0237', en: 'process', zh: '程式', level: 1, source: 'ecdict-v1' },
  { id: 'v0238', en: 'music', zh: '音樂', level: 1, source: 'ecdict-v1' },
  { id: 'v0239', en: 'including', zh: '包含', level: 1, source: 'ecdict-v1' },
  { id: 'v0240', en: 'consider', zh: '考慮', level: 1, source: 'ecdict-v1' },
  { id: 'v0241', en: 'appear', zh: '出現', level: 1, source: 'ecdict-v1' },
  { id: 'v0242', en: 'actually', zh: '事實上', level: 1, source: 'ecdict-v1' },
  { id: 'v0243', en: 'buy', zh: '買', level: 1, source: 'ecdict-v1' },
  { id: 'v0244', en: 'probably', zh: '大概', level: 1, source: 'ecdict-v1' },
  { id: 'v0245', en: 'wait', zh: '等待', level: 1, source: 'ecdict-v1' },
  { id: 'v0246', en: 'market', zh: '市場', level: 1, source: 'ecdict-v1' },
  { id: 'v0247', en: 'die', zh: '死亡', level: 1, source: 'ecdict-v1' },
  { id: 'v0248', en: 'send', zh: '傳送', level: 1, source: 'ecdict-v1' },
  { id: 'v0249', en: 'expect', zh: '預期', level: 1, source: 'ecdict-v1' },
  { id: 'v0250', en: 'sense', zh: '感應', level: 1, source: 'ecdict-v1' },
  { id: 'v0251', en: 'build', zh: '建立', level: 1, source: 'ecdict-v1' },
  { id: 'v0252', en: 'stay', zh: '停留', level: 1, source: 'ecdict-v1' },
  { id: 'v0253', en: 'fall', zh: '落下', level: 1, source: 'ecdict-v1' },
  { id: 'v0254', en: 'plan', zh: '計劃', level: 1, source: 'ecdict-v1' },
  { id: 'v0255', en: 'cut', zh: '切口', level: 1, source: 'ecdict-v1' },
  { id: 'v0256', en: 'college', zh: '學院', level: 1, source: 'ecdict-v1' },
  { id: 'v0257', en: 'interest', zh: '興趣', level: 1, source: 'ecdict-v1' },
  { id: 'v0258', en: 'course', zh: '課程', level: 1, source: 'ecdict-v1' },
  { id: 'v0259', en: 'someone', zh: '有人', level: 1, source: 'ecdict-v1' },
  { id: 'v0260', en: 'experience', zh: '經歷', level: 1, source: 'ecdict-v1' },
  { id: 'v0261', en: 'date', zh: '日期', level: 2, source: 'ecdict-v1' },
  { id: 'v0262', en: 'generally', zh: '通常', level: 2, source: 'ecdict-v1' },
  { id: 'v0263', en: 'sorry', zh: '難過的', level: 2, source: 'ecdict-v1' },
  { id: 'v0264', en: 'crisis', zh: '危機', level: 2, source: 'ecdict-v1' },
  { id: 'v0265', en: 'complete', zh: '完全的', level: 2, source: 'ecdict-v1' },
  { id: 'v0266', en: 'fan', zh: '風扇', level: 2, source: 'ecdict-v1' },
  { id: 'v0267', en: 'stick', zh: '棍', level: 2, source: 'ecdict-v1' },
  { id: 'v0268', en: 'define', zh: '定義', level: 2, source: 'ecdict-v1' },
  { id: 'v0269', en: 'easily', zh: '容易地', level: 2, source: 'ecdict-v1' },
  { id: 'v0270', en: 'hole', zh: '孔', level: 2, source: 'ecdict-v1' },
  { id: 'v0271', en: 'element', zh: '元件', level: 2, source: 'ecdict-v1' },
  { id: 'v0272', en: 'status', zh: '狀態', level: 2, source: 'ecdict-v1' },
  { id: 'v0273', en: 'vision', zh: '視覺', level: 2, source: 'ecdict-v1' },
  { id: 'v0274', en: 'normal', zh: '常態', level: 2, source: 'ecdict-v1' },
  { id: 'v0275', en: 'ship', zh: '船', level: 2, source: 'ecdict-v1' },
  { id: 'v0276', en: 'stone', zh: '石頭', level: 2, source: 'ecdict-v1' },
  { id: 'v0277', en: 'solution', zh: '解決', level: 2, source: 'ecdict-v1' },
  { id: 'v0278', en: 'slowly', zh: '慢慢地', level: 2, source: 'ecdict-v1' },
  { id: 'v0279', en: 'scale', zh: '刻度', level: 2, source: 'ecdict-v1' },
  { id: 'v0280', en: 'introduce', zh: '介紹', level: 2, source: 'ecdict-v1' },
  { id: 'v0281', en: 'driver', zh: '駕駛員', level: 2, source: 'ecdict-v1' },
  { id: 'v0282', en: 'spot', zh: '汙點', level: 2, source: 'ecdict-v1' },
  { id: 'v0283', en: 'lack', zh: '缺乏', level: 2, source: 'ecdict-v1' },
  { id: 'v0284', en: 'ice', zh: '冰', level: 2, source: 'ecdict-v1' },
  { id: 'v0285', en: 'drink', zh: '飲料', level: 2, source: 'ecdict-v1' },
  { id: 'v0286', en: 'sun', zh: '太陽', level: 2, source: 'ecdict-v1' },
  { id: 'v0287', en: 'distance', zh: '距離', level: 2, source: 'ecdict-v1' },
  { id: 'v0288', en: 'wood', zh: '木材', level: 2, source: 'ecdict-v1' },
  { id: 'v0289', en: 'truck', zh: '卡車', level: 2, source: 'ecdict-v1' },
  { id: 'v0290', en: 'handle', zh: '柄', level: 2, source: 'ecdict-v1' },
  { id: 'v0291', en: 'mountain', zh: '山', level: 2, source: 'ecdict-v1' },
  { id: 'v0292', en: 'survey', zh: '縱覽', level: 2, source: 'ecdict-v1' },
  { id: 'v0293', en: 'supposed', zh: '想像上的', level: 2, source: 'ecdict-v1' },
  { id: 'v0294', en: 'tradition', zh: '傳說', level: 2, source: 'ecdict-v1' },
  { id: 'v0295', en: 'winter', zh: '冬季', level: 2, source: 'ecdict-v1' },
  { id: 'v0296', en: 'village', zh: '村莊', level: 2, source: 'ecdict-v1' },
  { id: 'v0297', en: 'refuse', zh: '拒絕', level: 2, source: 'ecdict-v1' },
  { id: 'v0298', en: 'sales', zh: '銷售的', level: 2, source: 'ecdict-v1' },
  { id: 'v0299', en: 'roll', zh: '卷', level: 2, source: 'ecdict-v1' },
  { id: 'v0300', en: 'communication', zh: '交流', level: 2, source: 'ecdict-v1' },
  { id: 'v0301', en: 'screen', zh: '幕', level: 2, source: 'ecdict-v1' },
  { id: 'v0302', en: 'gain', zh: '增益', level: 2, source: 'ecdict-v1' },
  { id: 'v0303', en: 'resident', zh: '居民', level: 2, source: 'ecdict-v1' },
  { id: 'v0304', en: 'hide', zh: '獸皮', level: 2, source: 'ecdict-v1' },
  { id: 'v0305', en: 'gold', zh: '黃金', level: 2, source: 'ecdict-v1' },
  { id: 'v0306', en: 'club', zh: '俱樂部', level: 2, source: 'ecdict-v1' },
  { id: 'v0307', en: 'farm', zh: '農場', level: 2, source: 'ecdict-v1' },
  { id: 'v0308', en: 'potential', zh: '潛在性', level: 2, source: 'ecdict-v1' },
  { id: 'v0309', en: 'presence', zh: '出席', level: 2, source: 'ecdict-v1' },
  { id: 'v0310', en: 'independent', zh: '獨立自主者', level: 2, source: 'ecdict-v1' },
  { id: 'v0311', en: 'shape', zh: '形狀', level: 2, source: 'ecdict-v1' },
  { id: 'v0312', en: 'reader', zh: '讀者', level: 2, source: 'ecdict-v1' },
  { id: 'v0313', en: 'contract', zh: '合約', level: 2, source: 'ecdict-v1' },
  { id: 'v0314', en: 'crowd', zh: '群眾', level: 2, source: 'ecdict-v1' },
  { id: 'v0315', en: 'express', zh: '快車', level: 2, source: 'ecdict-v1' },
  { id: 'v0316', en: 'willing', zh: '樂意的', level: 2, source: 'ecdict-v1' },
  { id: 'v0317', en: 'previous', zh: '早先的', level: 2, source: 'ecdict-v1' },
  { id: 'v0318', en: 'band', zh: '帶子', level: 2, source: 'ecdict-v1' },
  { id: 'v0319', en: 'obviously', zh: '顯而易見地', level: 2, source: 'ecdict-v1' },
  { id: 'v0320', en: 'horse', zh: '馬', level: 2, source: 'ecdict-v1' },
  { id: 'v0321', en: 'interested', zh: '感興趣的', level: 2, source: 'ecdict-v1' },
  { id: 'v0322', en: 'target', zh: '目標', level: 2, source: 'ecdict-v1' },
  { id: 'v0323', en: 'prison', zh: '監獄', level: 2, source: 'ecdict-v1' },
  { id: 'v0324', en: 'ride', zh: '騎馬', level: 2, source: 'ecdict-v1' },
  { id: 'v0325', en: 'guard', zh: '守衛者', level: 2, source: 'ecdict-v1' },
  { id: 'v0326', en: 'terms', zh: '條件', level: 2, source: 'ecdict-v1' },
  { id: 'v0327', en: 'reporter', zh: '記者', level: 2, source: 'ecdict-v1' },
  { id: 'v0328', en: 'demand', zh: '要求', level: 2, source: 'ecdict-v1' },
  { id: 'v0329', en: 'deliver', zh: '遞送', level: 2, source: 'ecdict-v1' },
  { id: 'v0330', en: 'text', zh: '文本', level: 2, source: 'ecdict-v1' },
  { id: 'v0331', en: 'tool', zh: '工具', level: 2, source: 'ecdict-v1' },
  { id: 'v0332', en: 'wild', zh: '荒野', level: 2, source: 'ecdict-v1' },
  { id: 'v0333', en: 'vehicle', zh: '交通工具', level: 2, source: 'ecdict-v1' },
  { id: 'v0334', en: 'observe', zh: '覺察到', level: 2, source: 'ecdict-v1' },
  { id: 'v0335', en: 'flight', zh: '飛行', level: 2, source: 'ecdict-v1' },
  { id: 'v0336', en: 'facility', zh: '容易', level: 2, source: 'ecdict-v1' },
  { id: 'v0337', en: 'average', zh: '平均', level: 2, source: 'ecdict-v1' },
  { id: 'v0338', en: 'emerge', zh: '浮現', level: 2, source: 'ecdict-v1' },
  { id: 'v0339', en: 'advantage', zh: '優點', level: 2, source: 'ecdict-v1' },
  { id: 'v0340', en: 'quick', zh: '快的', level: 2, source: 'ecdict-v1' },
  { id: 'v0341', en: 'leadership', zh: '領導能力', level: 2, source: 'ecdict-v1' },
  { id: 'v0342', en: 'earn', zh: '賺得', level: 2, source: 'ecdict-v1' },
  { id: 'v0343', en: 'pound', zh: '磅', level: 2, source: 'ecdict-v1' },
  { id: 'v0344', en: 'basis', zh: '基礎', level: 2, source: 'ecdict-v1' },
  { id: 'v0345', en: 'bright', zh: '明亮的', level: 2, source: 'ecdict-v1' },
  { id: 'v0346', en: 'operate', zh: '操作', level: 2, source: 'ecdict-v1' },
  { id: 'v0347', en: 'guest', zh: '客人', level: 2, source: 'ecdict-v1' },
  { id: 'v0348', en: 'sample', zh: '樣品', level: 2, source: 'ecdict-v1' },
  { id: 'v0349', en: 'contribute', zh: '有助於', level: 2, source: 'ecdict-v1' },
  { id: 'v0350', en: 'block', zh: '街區', level: 2, source: 'ecdict-v1' },
  { id: 'v0351', en: 'protection', zh: '保護', level: 2, source: 'ecdict-v1' },
  { id: 'v0352', en: 'settle', zh: '有背長椅', level: 2, source: 'ecdict-v1' },
  { id: 'v0353', en: 'feed', zh: '飼料', level: 2, source: 'ecdict-v1' },
  { id: 'v0354', en: 'collect', zh: '收集', level: 2, source: 'ecdict-v1' },
  { id: 'v0355', en: 'additional', zh: '附加的', level: 2, source: 'ecdict-v1' },
  { id: 'v0356', en: 'highly', zh: '非常', level: 2, source: 'ecdict-v1' },
  { id: 'v0357', en: 'identity', zh: '身份', level: 2, source: 'ecdict-v1' },
  { id: 'v0358', en: 'title', zh: '頭銜', level: 2, source: 'ecdict-v1' },
  { id: 'v0359', en: 'lesson', zh: '課', level: 2, source: 'ecdict-v1' },
  { id: 'v0360', en: 'faith', zh: '信心', level: 2, source: 'ecdict-v1' },
  { id: 'v0361', en: 'river', zh: '河', level: 2, source: 'ecdict-v1' },
  { id: 'v0362', en: 'photo', zh: '相片', level: 2, source: 'ecdict-v1' },
  { id: 'v0363', en: 'promote', zh: '促進', level: 2, source: 'ecdict-v1' },
  { id: 'v0364', en: 'count', zh: '計算', level: 2, source: 'ecdict-v1' },
  { id: 'v0365', en: 'tomorrow', zh: '明天', level: 2, source: 'ecdict-v1' },
  { id: 'v0366', en: 'technique', zh: '技巧', level: 2, source: 'ecdict-v1' },
  { id: 'v0367', en: 'path', zh: '路徑', level: 2, source: 'ecdict-v1' },
  { id: 'v0368', en: 'ear', zh: '耳朵', level: 2, source: 'ecdict-v1' },
  { id: 'v0369', en: 'shop', zh: '商店', level: 2, source: 'ecdict-v1' },
  { id: 'v0370', en: 'folk', zh: '人們', level: 2, source: 'ecdict-v1' },
  { id: 'v0371', en: 'principle', zh: '原則', level: 2, source: 'ecdict-v1' },
  { id: 'v0372', en: 'lift', zh: '舉起', level: 2, source: 'ecdict-v1' },
  { id: 'v0373', en: 'border', zh: '邊緣', level: 2, source: 'ecdict-v1' },
  { id: 'v0374', en: 'competition', zh: '競爭', level: 2, source: 'ecdict-v1' },
  { id: 'v0375', en: 'jump', zh: '跳躍', level: 2, source: 'ecdict-v1' },
  { id: 'v0376', en: 'gather', zh: '集合', level: 2, source: 'ecdict-v1' },
  { id: 'v0377', en: 'limit', zh: '界限', level: 2, source: 'ecdict-v1' },
  { id: 'v0378', en: 'fit', zh: '適宜', level: 2, source: 'ecdict-v1' },
  { id: 'v0379', en: 'cry', zh: '叫聲', level: 2, source: 'ecdict-v1' },
  { id: 'v0380', en: 'equipment', zh: '裝備', level: 2, source: 'ecdict-v1' },
  { id: 'v0381', en: 'worth', zh: '價值', level: 2, source: 'ecdict-v1' },
  { id: 'v0382', en: 'associate', zh: '同伴', level: 2, source: 'ecdict-v1' },
  { id: 'v0383', en: 'critic', zh: '批評家', level: 2, source: 'ecdict-v1' },
  { id: 'v0384', en: 'warm', zh: '暖和的', level: 2, source: 'ecdict-v1' },
  { id: 'v0385', en: 'aspect', zh: '外觀', level: 2, source: 'ecdict-v1' },
  { id: 'v0386', en: 'insist', zh: '堅持', level: 2, source: 'ecdict-v1' },
  { id: 'v0387', en: 'failure', zh: '失敗', level: 2, source: 'ecdict-v1' },
  { id: 'v0388', en: 'annual', zh: '年刊', level: 2, source: 'ecdict-v1' },
  { id: 'v0389', en: 'comment', zh: '註解', level: 2, source: 'ecdict-v1' },
  { id: 'v0390', en: 'affair', zh: '事件', level: 2, source: 'ecdict-v1' },
  { id: 'v0391', en: 'responsible', zh: '有責任的', level: 2, source: 'ecdict-v1' },
  { id: 'v0392', en: 'regular', zh: '規則的', level: 2, source: 'ecdict-v1' },
  { id: 'v0393', en: 'spread', zh: '傳播', level: 2, source: 'ecdict-v1' },
  { id: 'v0394', en: 'chairman', zh: '主席', level: 2, source: 'ecdict-v1' },
  { id: 'v0395', en: 'baseball', zh: '棒球', level: 2, source: 'ecdict-v1' },
  { id: 'v0396', en: 'soft', zh: '軟的', level: 2, source: 'ecdict-v1' },
  { id: 'v0397', en: 'ignore', zh: '不理睬', level: 2, source: 'ecdict-v1' },
  { id: 'v0398', en: 'egg', zh: '蛋', level: 2, source: 'ecdict-v1' },
  { id: 'v0399', en: 'belief', zh: '信念', level: 2, source: 'ecdict-v1' },
  { id: 'v0400', en: 'demonstrate', zh: '示範', level: 2, source: 'ecdict-v1' },
  { id: 'v0401', en: 'anybody', zh: '任何人', level: 2, source: 'ecdict-v1' },
  { id: 'v0402', en: 'murder', zh: '謀殺', level: 2, source: 'ecdict-v1' },
  { id: 'v0403', en: 'gift', zh: '禮物', level: 2, source: 'ecdict-v1' },
  { id: 'v0404', en: 'religion', zh: '宗教', level: 2, source: 'ecdict-v1' },
  { id: 'v0405', en: 'review', zh: '檢討', level: 2, source: 'ecdict-v1' },
  { id: 'v0406', en: 'editor', zh: '編者', level: 2, source: 'ecdict-v1' },
  { id: 'v0407', en: 'engage', zh: '答應', level: 2, source: 'ecdict-v1' },
  { id: 'v0408', en: 'coffee', zh: '咖啡', level: 2, source: 'ecdict-v1' },
  { id: 'v0409', en: 'document', zh: '檔案', level: 2, source: 'ecdict-v1' },
  { id: 'v0410', en: 'speed', zh: '速率', level: 2, source: 'ecdict-v1' },
  { id: 'v0411', en: 'cross', zh: '十字架', level: 2, source: 'ecdict-v1' },
  { id: 'v0412', en: 'influence', zh: '影響力', level: 2, source: 'ecdict-v1' },
  { id: 'v0413', en: 'anyway', zh: '無論如何', level: 2, source: 'ecdict-v1' },
  { id: 'v0414', en: 'commit', zh: '委託', level: 2, source: 'ecdict-v1' },
  { id: 'v0415', en: 'threaten', zh: '恐嚇', level: 2, source: 'ecdict-v1' },
  { id: 'v0416', en: 'female', zh: '女性', level: 2, source: 'ecdict-v1' },
  { id: 'v0417', en: 'youth', zh: '年輕', level: 2, source: 'ecdict-v1' },
  { id: 'v0418', en: 'wave', zh: '波', level: 2, source: 'ecdict-v1' },
  { id: 'v0419', en: 'afraid', zh: '害怕的', level: 2, source: 'ecdict-v1' },
  { id: 'v0420', en: 'quarter', zh: '四分之一', level: 2, source: 'ecdict-v1' },
  { id: 'v0421', en: 'background', zh: '背景', level: 2, source: 'ecdict-v1' },
  { id: 'v0422', en: 'native', zh: '本地人', level: 2, source: 'ecdict-v1' },
  { id: 'v0423', en: 'broad', zh: '寬廣的', level: 2, source: 'ecdict-v1' },
  { id: 'v0424', en: 'wonderful', zh: '令人驚奇的', level: 2, source: 'ecdict-v1' },
  { id: 'v0425', en: 'deny', zh: '否認', level: 2, source: 'ecdict-v1' },
  { id: 'v0426', en: 'apparently', zh: '表面上', level: 2, source: 'ecdict-v1' },
  { id: 'v0427', en: 'slightly', zh: '些微地', level: 2, source: 'ecdict-v1' },
  { id: 'v0428', en: 'reaction', zh: '反應', level: 2, source: 'ecdict-v1' },
  { id: 'v0429', en: 'twice', zh: '兩次', level: 2, source: 'ecdict-v1' },
  { id: 'v0430', en: 'suit', zh: '套裝', level: 2, source: 'ecdict-v1' },
  { id: 'v0431', en: 'perspective', zh: '遠景', level: 2, source: 'ecdict-v1' },
  { id: 'v0432', en: 'growing', zh: '成長的', level: 2, source: 'ecdict-v1' },
  { id: 'v0433', en: 'blow', zh: '吹', level: 2, source: 'ecdict-v1' },
  { id: 'v0434', en: 'construction', zh: '建築', level: 2, source: 'ecdict-v1' },
  { id: 'v0435', en: 'intelligence', zh: '智力', level: 2, source: 'ecdict-v1' },
  { id: 'v0436', en: 'destroy', zh: '破壞', level: 2, source: 'ecdict-v1' },
  { id: 'v0437', en: 'cook', zh: '廚子', level: 2, source: 'ecdict-v1' },
  { id: 'v0438', en: 'connection', zh: '連線', level: 2, source: 'ecdict-v1' },
  { id: 'v0439', en: 'burn', zh: '燒', level: 2, source: 'ecdict-v1' },
  { id: 'v0440', en: 'shoe', zh: '鞋', level: 2, source: 'ecdict-v1' },
  { id: 'v0441', en: 'neighbor', zh: '鄰居', level: 2, source: 'ecdict-v1' },
  { id: 'v0442', en: 'grade', zh: '等級', level: 2, source: 'ecdict-v1' },
  { id: 'v0443', en: 'context', zh: '上下文', level: 2, source: 'ecdict-v1' },
  { id: 'v0444', en: 'committee', zh: '委員會', level: 2, source: 'ecdict-v1' },
  { id: 'v0445', en: 'mistake', zh: '錯誤', level: 2, source: 'ecdict-v1' },
  { id: 'v0446', en: 'location', zh: '位置', level: 2, source: 'ecdict-v1' },
  { id: 'v0447', en: 'clothes', zh: '衣服', level: 2, source: 'ecdict-v1' },
  { id: 'v0448', en: 'quiet', zh: '安靜', level: 2, source: 'ecdict-v1' },
  { id: 'v0449', en: 'dress', zh: '服裝', level: 2, source: 'ecdict-v1' },
  { id: 'v0450', en: 'promise', zh: '諾言', level: 2, source: 'ecdict-v1' },
  { id: 'v0451', en: 'aware', zh: '知道的', level: 2, source: 'ecdict-v1' },
  { id: 'v0452', en: 'function', zh: '官能', level: 2, source: 'ecdict-v1' },
  { id: 'v0453', en: 'bone', zh: '骨頭', level: 2, source: 'ecdict-v1' },
  { id: 'v0454', en: 'active', zh: '活躍的', level: 2, source: 'ecdict-v1' },
  { id: 'v0455', en: 'extend', zh: '擴充', level: 2, source: 'ecdict-v1' },
  { id: 'v0456', en: 'chief', zh: '領袖', level: 2, source: 'ecdict-v1' },
  { id: 'v0457', en: 'combine', zh: '聯合', level: 2, source: 'ecdict-v1' },
  { id: 'v0458', en: 'wine', zh: '葡萄酒', level: 2, source: 'ecdict-v1' },
  { id: 'v0459', en: 'cool', zh: '涼爽', level: 2, source: 'ecdict-v1' },
  { id: 'v0460', en: 'voter', zh: '選民', level: 2, source: 'ecdict-v1' },
  { id: 'v0461', en: 'bus', zh: '公共汽車', level: 2, source: 'ecdict-v1' },
  { id: 'v0462', en: 'learning', zh: '學問', level: 2, source: 'ecdict-v1' },
  { id: 'v0463', en: 'hell', zh: '地獄', level: 2, source: 'ecdict-v1' },
  { id: 'v0464', en: 'dangerous', zh: '危險的', level: 2, source: 'ecdict-v1' },
  { id: 'v0465', en: 'remind', zh: '提醒', level: 2, source: 'ecdict-v1' },
  { id: 'v0466', en: 'moral', zh: '道德', level: 2, source: 'ecdict-v1' },
  { id: 'v0467', en: 'united', zh: '聯合的', level: 2, source: 'ecdict-v1' },
  { id: 'v0468', en: 'relatively', zh: '相對地', level: 2, source: 'ecdict-v1' },
  { id: 'v0469', en: 'victory', zh: '勝利', level: 2, source: 'ecdict-v1' },
  { id: 'v0470', en: 'academic', zh: '學院的', level: 2, source: 'ecdict-v1' },
  { id: 'v0471', en: 'healthy', zh: '健康的', level: 2, source: 'ecdict-v1' },
  { id: 'v0472', en: 'negative', zh: '否定', level: 2, source: 'ecdict-v1' },
  { id: 'v0473', en: 'following', zh: '下列各項', level: 2, source: 'ecdict-v1' },
  { id: 'v0474', en: 'historical', zh: '歷史的', level: 2, source: 'ecdict-v1' },
  { id: 'v0475', en: 'medicine', zh: '藥', level: 2, source: 'ecdict-v1' },
  { id: 'v0476', en: 'tour', zh: '旅遊', level: 2, source: 'ecdict-v1' },
  { id: 'v0477', en: 'depend', zh: '靠', level: 2, source: 'ecdict-v1' },
  { id: 'v0478', en: 'grab', zh: '抓握', level: 2, source: 'ecdict-v1' },
  { id: 'v0479', en: 'direct', zh: '直接的', level: 2, source: 'ecdict-v1' },
  { id: 'v0480', en: 'classroom', zh: '教室', level: 2, source: 'ecdict-v1' },
  { id: 'v0481', en: 'contact', zh: '聯絡', level: 2, source: 'ecdict-v1' },
  { id: 'v0482', en: 'justice', zh: '正義', level: 2, source: 'ecdict-v1' },
  { id: 'v0483', en: 'participate', zh: '參加', level: 2, source: 'ecdict-v1' },
  { id: 'v0484', en: 'daily', zh: '每日的', level: 2, source: 'ecdict-v1' },
  { id: 'v0485', en: 'fair', zh: '展覽會', level: 2, source: 'ecdict-v1' },
  { id: 'v0486', en: 'pair', zh: '一雙', level: 2, source: 'ecdict-v1' },
  { id: 'v0487', en: 'famous', zh: '出名的', level: 2, source: 'ecdict-v1' },
  { id: 'v0488', en: 'exercise', zh: '行使', level: 2, source: 'ecdict-v1' },
  { id: 'v0489', en: 'knee', zh: '膝', level: 2, source: 'ecdict-v1' },
  { id: 'v0490', en: 'flower', zh: '花', level: 2, source: 'ecdict-v1' },
  { id: 'v0491', en: 'hire', zh: '租金', level: 2, source: 'ecdict-v1' },
  { id: 'v0492', en: 'familiar', zh: '熟悉的', level: 2, source: 'ecdict-v1' },
  { id: 'v0493', en: 'appropriate', zh: '適當的', level: 2, source: 'ecdict-v1' },
  { id: 'v0494', en: 'supply', zh: '補給', level: 2, source: 'ecdict-v1' },
  { id: 'v0495', en: 'fully', zh: '十分地', level: 2, source: 'ecdict-v1' },
  { id: 'v0496', en: 'actor', zh: '男演員', level: 2, source: 'ecdict-v1' },
  { id: 'v0497', en: 'birth', zh: '出生', level: 2, source: 'ecdict-v1' },
  { id: 'v0498', en: 'search', zh: '搜尋', level: 2, source: 'ecdict-v1' },
  { id: 'v0499', en: 'democracy', zh: '民主政治', level: 2, source: 'ecdict-v1' },
  { id: 'v0500', en: 'eastern', zh: '東方人', level: 2, source: 'ecdict-v1' },
  { id: 'v0501', en: 'primary', zh: '最主要者', level: 2, source: 'ecdict-v1' },
  { id: 'v0502', en: 'yesterday', zh: '昨天', level: 2, source: 'ecdict-v1' },
  { id: 'v0503', en: 'circle', zh: '圓周', level: 2, source: 'ecdict-v1' },
  { id: 'v0504', en: 'device', zh: '裝置', level: 2, source: 'ecdict-v1' },
  { id: 'v0505', en: 'progress', zh: '進步', level: 2, source: 'ecdict-v1' },
  { id: 'v0506', en: 'bottom', zh: '底部', level: 2, source: 'ecdict-v1' },
  { id: 'v0507', en: 'island', zh: '島', level: 2, source: 'ecdict-v1' },
  { id: 'v0508', en: 'exchange', zh: '交換', level: 2, source: 'ecdict-v1' },
  { id: 'v0509', en: 'clean', zh: '乾淨的', level: 2, source: 'ecdict-v1' },
  { id: 'v0510', en: 'studio', zh: '工作室', level: 2, source: 'ecdict-v1' },
  { id: 'v0511', en: 'county', zh: '縣', level: 2, source: 'ecdict-v1' },
  { id: 'v0512', en: 'train', zh: '火車', level: 2, source: 'ecdict-v1' },
  { id: 'v0513', en: 'lady', zh: '淑女', level: 2, source: 'ecdict-v1' },
  { id: 'v0514', en: 'colleague', zh: '同事', level: 2, source: 'ecdict-v1' },
  { id: 'v0515', en: 'application', zh: '應用', level: 2, source: 'ecdict-v1' },
  { id: 'v0516', en: 'lean', zh: '瘦肉', level: 2, source: 'ecdict-v1' },
  { id: 'v0517', en: 'neck', zh: '脖子', level: 2, source: 'ecdict-v1' },
  { id: 'v0518', en: 'damage', zh: '損害', level: 2, source: 'ecdict-v1' },
  { id: 'v0519', en: 'plastic', zh: '塑膠', level: 2, source: 'ecdict-v1' },
  { id: 'v0520', en: 'tall', zh: '高的', level: 2, source: 'ecdict-v1' },
  { id: 'v0521', en: 'humanity', zh: '人性', level: 3, source: 'ecdict-v1' },
  { id: 'v0522', en: 'correlation', zh: '相互關係', level: 3, source: 'ecdict-v1' },
  { id: 'v0523', en: 'developer', zh: '開發者', level: 3, source: 'ecdict-v1' },
  { id: 'v0524', en: 'reliable', zh: '可靠的', level: 3, source: 'ecdict-v1' },
  { id: 'v0525', en: 'beef', zh: '牛肉', level: 3, source: 'ecdict-v1' },
  { id: 'v0526', en: 'excitement', zh: '刺激', level: 3, source: 'ecdict-v1' },
  { id: 'v0527', en: 'architecture', zh: '建築學', level: 3, source: 'ecdict-v1' },
  { id: 'v0528', en: 'administrative', zh: '管理的', level: 3, source: 'ecdict-v1' },
  { id: 'v0529', en: 'occasional', zh: '偶然的', level: 3, source: 'ecdict-v1' },
  { id: 'v0530', en: 'elbow', zh: '手肘', level: 3, source: 'ecdict-v1' },
  { id: 'v0531', en: 'deadly', zh: '致命的', level: 3, source: 'ecdict-v1' },
  { id: 'v0532', en: 'allegation', zh: '斷言', level: 3, source: 'ecdict-v1' },
  { id: 'v0533', en: 'confuse', zh: '使混亂', level: 3, source: 'ecdict-v1' },
  { id: 'v0534', en: 'airplane', zh: '飛機', level: 3, source: 'ecdict-v1' },
  { id: 'v0535', en: 'monthly', zh: '月刊', level: 3, source: 'ecdict-v1' },
  { id: 'v0536', en: 'duck', zh: '鴨子', level: 3, source: 'ecdict-v1' },
  { id: 'v0537', en: 'dose', zh: '劑量', level: 3, source: 'ecdict-v1' },
  { id: 'v0538', en: 'initiate', zh: '入會', level: 3, source: 'ecdict-v1' },
  { id: 'v0539', en: 'plead', zh: '辯護', level: 3, source: 'ecdict-v1' },
  { id: 'v0540', en: 'lecture', zh: '演講', level: 3, source: 'ecdict-v1' },
  { id: 'v0541', en: 'sixth', zh: '第六', level: 3, source: 'ecdict-v1' },
  { id: 'v0542', en: 'mainstream', zh: '主流', level: 3, source: 'ecdict-v1' },
  { id: 'v0543', en: 'sandwich', zh: '三明治', level: 3, source: 'ecdict-v1' },
  { id: 'v0544', en: 'implementation', zh: '安裝啟用', level: 3, source: 'ecdict-v1' },
  { id: 'v0545', en: 'suburb', zh: '市郊住宅區', level: 3, source: 'ecdict-v1' },
  { id: 'v0546', en: 'trunk', zh: '樹幹', level: 3, source: 'ecdict-v1' },
  { id: 'v0547', en: 'motivate', zh: '給與動機', level: 3, source: 'ecdict-v1' },
  { id: 'v0548', en: 'swallow', zh: '燕子', level: 3, source: 'ecdict-v1' },
  { id: 'v0549', en: 'longtime', zh: '長時間的', level: 3, source: 'ecdict-v1' },
  { id: 'v0550', en: 'render', zh: '回報', level: 3, source: 'ecdict-v1' },
  { id: 'v0551', en: 'trap', zh: '圈套', level: 3, source: 'ecdict-v1' },
  { id: 'v0552', en: 'restrict', zh: '限制', level: 3, source: 'ecdict-v1' },
  { id: 'v0553', en: 'cloth', zh: '布料', level: 3, source: 'ecdict-v1' },
  { id: 'v0554', en: 'seemingly', zh: '看來似乎', level: 3, source: 'ecdict-v1' },
  { id: 'v0555', en: 'legislative', zh: '立法機構', level: 3, source: 'ecdict-v1' },
  { id: 'v0556', en: 'effectiveness', zh: '效力', level: 3, source: 'ecdict-v1' },
  { id: 'v0557', en: 'lens', zh: '透鏡', level: 3, source: 'ecdict-v1' },
  { id: 'v0558', en: 'enforce', zh: '強迫', level: 3, source: 'ecdict-v1' },
  { id: 'v0559', en: 'lend', zh: '借', level: 3, source: 'ecdict-v1' },
  { id: 'v0560', en: 'plain', zh: '平原', level: 3, source: 'ecdict-v1' },
  { id: 'v0561', en: 'inspector', zh: '檢查員', level: 3, source: 'ecdict-v1' },
  { id: 'v0562', en: 'fraud', zh: '欺騙', level: 3, source: 'ecdict-v1' },
  { id: 'v0563', en: 'contend', zh: '奮鬥', level: 3, source: 'ecdict-v1' },
  { id: 'v0564', en: 'strict', zh: '嚴厲的', level: 3, source: 'ecdict-v1' },
  { id: 'v0565', en: 'array', zh: '排列', level: 3, source: 'ecdict-v1' },
  { id: 'v0566', en: 'frankly', zh: '坦白地', level: 3, source: 'ecdict-v1' },
  { id: 'v0567', en: 'nail', zh: '釘子', level: 3, source: 'ecdict-v1' },
  { id: 'v0568', en: 'rat', zh: '鼠', level: 3, source: 'ecdict-v1' },
  { id: 'v0569', en: 'hallway', zh: '門廳', level: 3, source: 'ecdict-v1' },
  { id: 'v0570', en: 'burst', zh: '破裂', level: 3, source: 'ecdict-v1' },
  { id: 'v0571', en: 'inevitable', zh: '不可避免的', level: 3, source: 'ecdict-v1' },
  { id: 'v0572', en: 'cave', zh: '洞', level: 3, source: 'ecdict-v1' },
  { id: 'v0573', en: 'southwest', zh: '西南', level: 3, source: 'ecdict-v1' },
  { id: 'v0574', en: 'monster', zh: '怪物', level: 3, source: 'ecdict-v1' },
  { id: 'v0575', en: 'unexpected', zh: '料想不到的', level: 3, source: 'ecdict-v1' },
  { id: 'v0576', en: 'facilitate', zh: '使容易', level: 3, source: 'ecdict-v1' },
  { id: 'v0577', en: 'obstacle', zh: '障礙', level: 3, source: 'ecdict-v1' },
  { id: 'v0578', en: 'overwhelming', zh: '壓倒性的', level: 3, source: 'ecdict-v1' },
  { id: 'v0579', en: 'rip', zh: '裂痕', level: 3, source: 'ecdict-v1' },
  { id: 'v0580', en: 'herb', zh: '藥草', level: 3, source: 'ecdict-v1' },
  { id: 'v0581', en: 'crystal', zh: '水晶', level: 3, source: 'ecdict-v1' },
  { id: 'v0582', en: 'integration', zh: '綜合', level: 3, source: 'ecdict-v1' },
  { id: 'v0583', en: 'recession', zh: '後退', level: 3, source: 'ecdict-v1' },
  { id: 'v0584', en: 'motive', zh: '動機', level: 3, source: 'ecdict-v1' },
  { id: 'v0585', en: 'bitter', zh: '苦的', level: 3, source: 'ecdict-v1' },
  { id: 'v0586', en: 'written', zh: '書面的', level: 3, source: 'ecdict-v1' },
  { id: 'v0587', en: 'flood', zh: '洪水', level: 3, source: 'ecdict-v1' },
  { id: 'v0588', en: 'pen', zh: '鋼筆', level: 3, source: 'ecdict-v1' },
  { id: 'v0589', en: 'ownership', zh: '所有權', level: 3, source: 'ecdict-v1' },
  { id: 'v0590', en: 'nightmare', zh: '夢魘', level: 3, source: 'ecdict-v1' },
  { id: 'v0591', en: 'inspection', zh: '檢驗', level: 3, source: 'ecdict-v1' },
  { id: 'v0592', en: 'supervisor', zh: '管理者', level: 3, source: 'ecdict-v1' },
  { id: 'v0593', en: 'arena', zh: '角鬥場', level: 3, source: 'ecdict-v1' },
  { id: 'v0594', en: 'consult', zh: '商討', level: 3, source: 'ecdict-v1' },
  { id: 'v0595', en: 'possession', zh: '擁有', level: 3, source: 'ecdict-v1' },
  { id: 'v0596', en: 'diagnosis', zh: '診斷', level: 3, source: 'ecdict-v1' },
  { id: 'v0597', en: 'forgive', zh: '原諒', level: 3, source: 'ecdict-v1' },
  { id: 'v0598', en: 'consistently', zh: '堅固', level: 3, source: 'ecdict-v1' },
  { id: 'v0599', en: 'basement', zh: '地下室', level: 3, source: 'ecdict-v1' },
  { id: 'v0600', en: 'drift', zh: '漂流物', level: 3, source: 'ecdict-v1' },
  { id: 'v0601', en: 'drain', zh: '排水溝', level: 3, source: 'ecdict-v1' },
  { id: 'v0602', en: 'maximum', zh: '極點', level: 3, source: 'ecdict-v1' },
  { id: 'v0603', en: 'announcement', zh: '公告', level: 3, source: 'ecdict-v1' },
  { id: 'v0604', en: 'prosecution', zh: '執行', level: 3, source: 'ecdict-v1' },
  { id: 'v0605', en: 'questionnaire', zh: '調查表', level: 3, source: 'ecdict-v1' },
  { id: 'v0606', en: 'warrior', zh: '戰士', level: 3, source: 'ecdict-v1' },
  { id: 'v0607', en: 'prediction', zh: '預言', level: 3, source: 'ecdict-v1' },
  { id: 'v0608', en: 'hurry', zh: '匆忙', level: 3, source: 'ecdict-v1' },
  { id: 'v0609', en: 'mud', zh: '泥', level: 3, source: 'ecdict-v1' },
  { id: 'v0610', en: 'bacteria', zh: '細菌', level: 3, source: 'ecdict-v1' },
  { id: 'v0611', en: 'privilege', zh: '特權', level: 3, source: 'ecdict-v1' },
  { id: 'v0612', en: 'infrastructure', zh: '基礎結構', level: 3, source: 'ecdict-v1' },
  { id: 'v0613', en: 'outdoor', zh: '戶外的', level: 3, source: 'ecdict-v1' },
  { id: 'v0614', en: 'temple', zh: '聖堂', level: 3, source: 'ecdict-v1' },
  { id: 'v0615', en: 'broadcast', zh: '廣播', level: 3, source: 'ecdict-v1' },
  { id: 'v0616', en: 'suck', zh: '吸', level: 3, source: 'ecdict-v1' },
  { id: 'v0617', en: 'random', zh: '隨意', level: 3, source: 'ecdict-v1' },
  { id: 'v0618', en: 'curtain', zh: '帳', level: 3, source: 'ecdict-v1' },
  { id: 'v0619', en: 'wrist', zh: '手腕', level: 3, source: 'ecdict-v1' },
  { id: 'v0620', en: 'pond', zh: '池塘', level: 3, source: 'ecdict-v1' },
  { id: 'v0621', en: 'domain', zh: '領域', level: 3, source: 'ecdict-v1' },
  { id: 'v0622', en: 'guilt', zh: '罪行', level: 3, source: 'ecdict-v1' },
  { id: 'v0623', en: 'cattle', zh: '牛', level: 3, source: 'ecdict-v1' },
  { id: 'v0624', en: 'weird', zh: '怪異的', level: 3, source: 'ecdict-v1' },
  { id: 'v0625', en: 'minimum', zh: '最小的', level: 3, source: 'ecdict-v1' },
  { id: 'v0626', en: 'walking', zh: '步行', level: 3, source: 'ecdict-v1' },
  { id: 'v0627', en: 'fiscal', zh: '財政的', level: 3, source: 'ecdict-v1' },
  { id: 'v0628', en: 'dump', zh: '垃圾場', level: 3, source: 'ecdict-v1' },
  { id: 'v0629', en: 'skirt', zh: '裙子', level: 3, source: 'ecdict-v1' },
  { id: 'v0630', en: 'database', zh: '資料庫', level: 3, source: 'ecdict-v1' },
  { id: 'v0631', en: 'uncomfortable', zh: '不舒服的', level: 3, source: 'ecdict-v1' },
  { id: 'v0632', en: 'limb', zh: '四肢', level: 3, source: 'ecdict-v1' },
  { id: 'v0633', en: 'ideology', zh: '思想體系', level: 3, source: 'ecdict-v1' },
  { id: 'v0634', en: 'tune', zh: '歌曲', level: 3, source: 'ecdict-v1' },
  { id: 'v0635', en: 'continuing', zh: '繼續的', level: 3, source: 'ecdict-v1' },
  { id: 'v0636', en: 'railroad', zh: '鐵路', level: 3, source: 'ecdict-v1' },
  { id: 'v0637', en: 'endure', zh: '忍受', level: 3, source: 'ecdict-v1' },
  { id: 'v0638', en: 'harm', zh: '傷害', level: 3, source: 'ecdict-v1' },
  { id: 'v0639', en: 'radiation', zh: '輻射', level: 3, source: 'ecdict-v1' },
  { id: 'v0640', en: 'horn', zh: '角', level: 3, source: 'ecdict-v1' },
  { id: 'v0641', en: 'chronic', zh: '慢性的', level: 3, source: 'ecdict-v1' },
  { id: 'v0642', en: 'peaceful', zh: '平靜的', level: 3, source: 'ecdict-v1' },
  { id: 'v0643', en: 'replacement', zh: '歸還', level: 3, source: 'ecdict-v1' },
  { id: 'v0644', en: 'innovation', zh: '改革', level: 3, source: 'ecdict-v1' },
  { id: 'v0645', en: 'guitar', zh: '吉他', level: 3, source: 'ecdict-v1' },
  { id: 'v0646', en: 'strain', zh: '緊張', level: 3, source: 'ecdict-v1' },
  { id: 'v0647', en: 'behave', zh: '舉止端正', level: 3, source: 'ecdict-v1' },
  { id: 'v0648', en: 'administer', zh: '管理', level: 3, source: 'ecdict-v1' },
  { id: 'v0649', en: 'simultaneously', zh: '同時發生', level: 3, source: 'ecdict-v1' },
  { id: 'v0650', en: 'dancer', zh: '舞蹈演員', level: 3, source: 'ecdict-v1' },
  { id: 'v0651', en: 'pad', zh: '填補', level: 3, source: 'ecdict-v1' },
  { id: 'v0652', en: 'transmission', zh: '傳輸', level: 3, source: 'ecdict-v1' },
  { id: 'v0653', en: 'trigger', zh: '觸發器', level: 3, source: 'ecdict-v1' },
  { id: 'v0654', en: 'amendment', zh: '修訂', level: 3, source: 'ecdict-v1' },
  { id: 'v0655', en: 'await', zh: '等候', level: 3, source: 'ecdict-v1' },
  { id: 'v0656', en: 'retired', zh: '隱退的', level: 3, source: 'ecdict-v1' },
  { id: 'v0657', en: 'spill', zh: '溢位', level: 3, source: 'ecdict-v1' },
  { id: 'v0658', en: 'grateful', zh: '感謝的', level: 3, source: 'ecdict-v1' },
  { id: 'v0659', en: 'colony', zh: '殖民地', level: 3, source: 'ecdict-v1' },
  { id: 'v0660', en: 'adoption', zh: '採用', level: 3, source: 'ecdict-v1' },
  { id: 'v0661', en: 'convict', zh: '囚犯', level: 3, source: 'ecdict-v1' },
  { id: 'v0662', en: 'indigenous', zh: '本土的', level: 3, source: 'ecdict-v1' },
  { id: 'v0663', en: 'closed', zh: '關閉的', level: 3, source: 'ecdict-v1' },
  { id: 'v0664', en: 'towel', zh: '手巾', level: 3, source: 'ecdict-v1' },
  { id: 'v0665', en: 'particle', zh: '顆粒', level: 3, source: 'ecdict-v1' },
  { id: 'v0666', en: 'modify', zh: '修正', level: 3, source: 'ecdict-v1' },
  { id: 'v0667', en: 'prize', zh: '獎賞', level: 3, source: 'ecdict-v1' },
  { id: 'v0668', en: 'landing', zh: '登陸', level: 3, source: 'ecdict-v1' },
  { id: 'v0669', en: 'boost', zh: '推進', level: 3, source: 'ecdict-v1' },
  { id: 'v0670', en: 'bat', zh: '蝙蝠', level: 3, source: 'ecdict-v1' },
  { id: 'v0671', en: 'alarm', zh: '驚恐', level: 3, source: 'ecdict-v1' },
  { id: 'v0672', en: 'grip', zh: '緊握', level: 3, source: 'ecdict-v1' },
  { id: 'v0673', en: 'festival', zh: '節日的', level: 3, source: 'ecdict-v1' },
  { id: 'v0674', en: 'sweat', zh: '汗', level: 3, source: 'ecdict-v1' },
  { id: 'v0675', en: 'outer', zh: '外部的', level: 3, source: 'ecdict-v1' },
  { id: 'v0676', en: 'freshman', zh: '新手', level: 3, source: 'ecdict-v1' },
  { id: 'v0677', en: 'drunk', zh: '喝醉了的', level: 3, source: 'ecdict-v1' },
  { id: 'v0678', en: 'separation', zh: '分離', level: 3, source: 'ecdict-v1' },
  { id: 'v0679', en: 'traditionally', zh: '傳統上', level: 3, source: 'ecdict-v1' },
  { id: 'v0680', en: 'ballot', zh: '投票', level: 3, source: 'ecdict-v1' },
  { id: 'v0681', en: 'web', zh: '網', level: 3, source: 'ecdict-v1' },
  { id: 'v0682', en: 'southeast', zh: '東南', level: 3, source: 'ecdict-v1' },
  { id: 'v0683', en: 'intelligent', zh: '聰明的', level: 3, source: 'ecdict-v1' },
  { id: 'v0684', en: 'republic', zh: '共和國', level: 3, source: 'ecdict-v1' },
  { id: 'v0685', en: 'wherever', zh: '無論哪裡', level: 3, source: 'ecdict-v1' },
  { id: 'v0686', en: 'govern', zh: '統治', level: 3, source: 'ecdict-v1' },
  { id: 'v0687', en: 'driving', zh: '趕', level: 3, source: 'ecdict-v1' },
  { id: 'v0688', en: 'rhetoric', zh: '修辭', level: 3, source: 'ecdict-v1' },
  { id: 'v0689', en: 'convinced', zh: '確信的', level: 3, source: 'ecdict-v1' },
  { id: 'v0690', en: 'vitamin', zh: '維生素', level: 3, source: 'ecdict-v1' },
  { id: 'v0691', en: 'enthusiasm', zh: '巨大的熱情', level: 3, source: 'ecdict-v1' },
  { id: 'v0692', en: 'accommodate', zh: '使適應', level: 3, source: 'ecdict-v1' },
  { id: 'v0693', en: 'praise', zh: '讚美', level: 3, source: 'ecdict-v1' },
  { id: 'v0694', en: 'endless', zh: '不停的', level: 3, source: 'ecdict-v1' },
  { id: 'v0695', en: 'mandate', zh: '命令', level: 3, source: 'ecdict-v1' },
  { id: 'v0696', en: 'respectively', zh: '各自地', level: 3, source: 'ecdict-v1' },
  { id: 'v0697', en: 'chaos', zh: '大混亂', level: 3, source: 'ecdict-v1' },
  { id: 'v0698', en: 'uncertainty', zh: '不確定', level: 3, source: 'ecdict-v1' },
  { id: 'v0699', en: 'mechanical', zh: '機械的', level: 3, source: 'ecdict-v1' },
  { id: 'v0700', en: 'format', zh: '開本', level: 3, source: 'ecdict-v1' },
  { id: 'v0701', en: 'canvas', zh: '帆布', level: 3, source: 'ecdict-v1' },
  { id: 'v0702', en: 'forty', zh: '四十', level: 3, source: 'ecdict-v1' },
  { id: 'v0703', en: 'profound', zh: '極深的', level: 3, source: 'ecdict-v1' },
  { id: 'v0704', en: 'lobby', zh: '大廳', level: 3, source: 'ecdict-v1' },
  { id: 'v0705', en: 'trait', zh: '特徵', level: 3, source: 'ecdict-v1' },
  { id: 'v0706', en: 'currency', zh: '貨幣', level: 3, source: 'ecdict-v1' },
  { id: 'v0707', en: 'apologize', zh: '道歉', level: 3, source: 'ecdict-v1' },
  { id: 'v0708', en: 'reserve', zh: '儲備品', level: 3, source: 'ecdict-v1' },
  { id: 'v0709', en: 'beam', zh: '橫樑', level: 3, source: 'ecdict-v1' },
  { id: 'v0710', en: 'corruption', zh: '腐敗', level: 3, source: 'ecdict-v1' },
  { id: 'v0711', en: 'astronomer', zh: '天文學家', level: 3, source: 'ecdict-v1' },
  { id: 'v0712', en: 'contractor', zh: '立契約的人', level: 3, source: 'ecdict-v1' },
  { id: 'v0713', en: 'doctrine', zh: '教條', level: 3, source: 'ecdict-v1' },
  { id: 'v0714', en: 'genuine', zh: '真正的', level: 3, source: 'ecdict-v1' },
  { id: 'v0715', en: 'thumb', zh: '拇指', level: 3, source: 'ecdict-v1' },
  { id: 'v0716', en: 'unity', zh: '一致', level: 3, source: 'ecdict-v1' },
  { id: 'v0717', en: 'horrible', zh: '可怕的', level: 3, source: 'ecdict-v1' },
  { id: 'v0718', en: 'compromise', zh: '妥協', level: 3, source: 'ecdict-v1' },
  { id: 'v0719', en: 'behavioral', zh: '行為的', level: 3, source: 'ecdict-v1' },
  { id: 'v0720', en: 'bureau', zh: '局', level: 3, source: 'ecdict-v1' },
  { id: 'v0721', en: 'exclusive', zh: '排外的', level: 3, source: 'ecdict-v1' },
  { id: 'v0722', en: 'scatter', zh: '消散', level: 3, source: 'ecdict-v1' },
  { id: 'v0723', en: 'commonly', zh: '一般', level: 3, source: 'ecdict-v1' },
  { id: 'v0724', en: 'convey', zh: '傳達', level: 3, source: 'ecdict-v1' },
  { id: 'v0725', en: 'complexity', zh: '複雜', level: 3, source: 'ecdict-v1' },
  { id: 'v0726', en: 'fork', zh: '叉子', level: 3, source: 'ecdict-v1' },
  { id: 'v0727', en: 'twist', zh: '一扭', level: 3, source: 'ecdict-v1' },
  { id: 'v0728', en: 'disk', zh: '圓盤', level: 3, source: 'ecdict-v1' },
  { id: 'v0729', en: 'suspicion', zh: '懷疑', level: 3, source: 'ecdict-v1' },
  { id: 'v0730', en: 'relieve', zh: '減輕', level: 3, source: 'ecdict-v1' },
  { id: 'v0731', en: 'residence', zh: '住宅', level: 3, source: 'ecdict-v1' },
  { id: 'v0732', en: 'shame', zh: '羞恥', level: 3, source: 'ecdict-v1' },
  { id: 'v0733', en: 'meaningful', zh: '意味深長的', level: 3, source: 'ecdict-v1' },
  { id: 'v0734', en: 'sidewalk', zh: '人行道', level: 3, source: 'ecdict-v1' },
  { id: 'v0735', en: 'technological', zh: '技術的', level: 3, source: 'ecdict-v1' },
  { id: 'v0736', en: 'pleasant', zh: '愉快的', level: 3, source: 'ecdict-v1' },
  { id: 'v0737', en: 'signature', zh: '簽字', level: 3, source: 'ecdict-v1' },
  { id: 'v0738', en: 'suspend', zh: '懸', level: 3, source: 'ecdict-v1' },
  { id: 'v0739', en: 'rebel', zh: '叛徒', level: 3, source: 'ecdict-v1' },
  { id: 'v0740', en: 'spouse', zh: '配偶', level: 3, source: 'ecdict-v1' },
  { id: 'v0741', en: 'frozen', zh: '凍結的', level: 3, source: 'ecdict-v1' },
  { id: 'v0742', en: 'fluid', zh: '液體', level: 3, source: 'ecdict-v1' },
  { id: 'v0743', en: 'resume', zh: '重新開始', level: 3, source: 'ecdict-v1' },
  { id: 'v0744', en: 'theoretical', zh: '理論的', level: 3, source: 'ecdict-v1' },
  { id: 'v0745', en: 'sodium', zh: '鈉', level: 3, source: 'ecdict-v1' },
  { id: 'v0746', en: 'pension', zh: '養老金', level: 3, source: 'ecdict-v1' },
  { id: 'v0747', en: 'promotion', zh: '晉級', level: 3, source: 'ecdict-v1' },
  { id: 'v0748', en: 'delicate', zh: '細緻優雅的', level: 3, source: 'ecdict-v1' },
  { id: 'v0749', en: 'forehead', zh: '額', level: 3, source: 'ecdict-v1' },
  { id: 'v0750', en: 'electrical', zh: '電的', level: 3, source: 'ecdict-v1' },
  { id: 'v0751', en: 'rebuild', zh: '改建', level: 3, source: 'ecdict-v1' },
  { id: 'v0752', en: 'hook', zh: '鉤', level: 3, source: 'ecdict-v1' },
  { id: 'v0753', en: 'bounce', zh: '跳', level: 3, source: 'ecdict-v1' },
  { id: 'v0754', en: 'detective', zh: '偵探', level: 3, source: 'ecdict-v1' },
  { id: 'v0755', en: 'click', zh: '咔噠聲', level: 3, source: 'ecdict-v1' },
  { id: 'v0756', en: 'traveler', zh: '旅行者', level: 3, source: 'ecdict-v1' },
  { id: 'v0757', en: 'compensation', zh: '補償', level: 3, source: 'ecdict-v1' },
  { id: 'v0758', en: 'exit', zh: '出口', level: 3, source: 'ecdict-v1' },
  { id: 'v0759', en: 'dedicate', zh: '獻出', level: 3, source: 'ecdict-v1' },
  { id: 'v0760', en: 'attraction', zh: '吸引', level: 3, source: 'ecdict-v1' },
  { id: 'v0761', en: 'altogether', zh: '完全地', level: 3, source: 'ecdict-v1' },
  { id: 'v0762', en: 'pickup', zh: '拾起', level: 3, source: 'ecdict-v1' },
  { id: 'v0763', en: 'carve', zh: '雕刻', level: 3, source: 'ecdict-v1' },
  { id: 'v0764', en: 'needle', zh: '針', level: 3, source: 'ecdict-v1' },
  { id: 'v0765', en: 'belly', zh: '腹部', level: 3, source: 'ecdict-v1' },
  { id: 'v0766', en: 'scare', zh: '驚嚇', level: 3, source: 'ecdict-v1' },
  { id: 'v0767', en: 'timing', zh: '時間選擇', level: 3, source: 'ecdict-v1' },
  { id: 'v0768', en: 'portfolio', zh: '皮包', level: 3, source: 'ecdict-v1' },
  { id: 'v0769', en: 'shuttle', zh: '穿梭', level: 3, source: 'ecdict-v1' },
  { id: 'v0770', en: 'invisible', zh: '看不見的', level: 3, source: 'ecdict-v1' },
  { id: 'v0771', en: 'transaction', zh: '交易', level: 3, source: 'ecdict-v1' },
  { id: 'v0772', en: 'ankle', zh: '踝', level: 3, source: 'ecdict-v1' },
  { id: 'v0773', en: 'rescue', zh: '援救', level: 3, source: 'ecdict-v1' },
  { id: 'v0774', en: 'counterpart', zh: '副本', level: 3, source: 'ecdict-v1' },
  { id: 'v0775', en: 'historically', zh: '歷史上地', level: 3, source: 'ecdict-v1' },
  { id: 'v0776', en: 'mild', zh: '溫和的', level: 3, source: 'ecdict-v1' },
  { id: 'v0777', en: 'noon', zh: '正午', level: 3, source: 'ecdict-v1' },
  { id: 'v0778', en: 'identical', zh: '同一的', level: 3, source: 'ecdict-v1' },
  { id: 'v0779', en: 'doll', zh: '洋娃娃', level: 3, source: 'ecdict-v1' },
  { id: 'v0780', en: 'rider', zh: '騎手', level: 3, source: 'ecdict-v1' },
];

/** 例句。不是每個字都有——沒有的字答完就不顯示例句。 */
export const EXAMPLES: Readonly<Record<string, VocabExample>> = {
  v0001: { en: "I can't say.", zh: "我不能說。" },
  v0002: { en: "Get serious.", zh: "認真點。" },
  v0003: { en: "Make a list.", zh: "列一個列表。" },
  v0004: { en: "Yes, I know.", zh: "是的，我知道。" },
  v0005: { en: "No one came.", zh: "沒有人來了。" },
  v0006: { en: "I have time.", zh: "我有時間。" },
  v0007: { en: "Happy New Year!", zh: "新年快樂！" },
  v0008: { en: "Let me think.", zh: "讓我想一想。" },
  v0009: { en: "We're people.", zh: "我們是人。" },
  v0010: { en: "Take a peek!", zh: "瞧瞧吧！" },
  v0011: { en: "I can't see!", zh: "我看不見啊！" },
  v0012: { en: "Please come.", zh: "請來吧。" },
  v0013: { en: "Run off now!", zh: "落跑吧！" },
  v0014: { en: "I like fish.", zh: "我喜歡魚。" },
  v0015: { en: "Two women sing.", zh: "兩個女人唱著歌。" },
  v0016: { en: "I want more.", zh: "我想要更多。" },
  v0017: { en: "I want more.", zh: "我想要更多。" },
  v0018: { en: "Take his way.", zh: "採用他的方法。" },
  v0019: { en: "Look around.", zh: "四處看看。" },
  v0020: { en: "Ladies first.", zh: "女士優先。" },
  v0021: { en: "What is new?", zh: "有什麼新鮮事嗎？" },
  v0022: { en: "All day long.", zh: "一整天。" },
  v0023: { en: "Use caution.", zh: "小心！" },
  v0024: { en: "Man is mortal.", zh: "人固有一死。" },
  v0025: { en: "Can you find it?", zh: "你能找到它嗎？" },
  v0026: { en: "Hide that thing.", zh: "把那個東西藏起來。" },
  v0027: { en: "Give me five!", zh: "擊掌！" },
  v0028: { en: "Many thanks.", zh: "非常感謝！" },
  v0029: { en: "Is Tom well?", zh: "湯姆還好吧？" },
  v0030: { en: "Tell us more.", zh: "告訴我們多一點。" },
  v0031: { en: "Welcome back.", zh: "歡迎回來。" },
  v0032: { en: "That's good.", zh: "很好！" },
  v0033: { en: "I'm a woman.", zh: "我是女人。" },
  v0034: { en: "Life is fun.", zh: "人生是有趣的。" },
  v0035: { en: "Be a good child!", zh: "做個好孩子！" },
  v0036: { en: "Work slowly.", zh: "幹活慢點。" },
  v0037: { en: "Call me Tom!", zh: "叫我湯姆吧！" },
  v0038: { en: "Hello, world!", zh: "你好，世界！" },
  v0039: { en: "How's school?", zh: "學校怎麼樣？" },
  v0040: { en: "I'll try it.", zh: "我試試。" },
  v0041: { en: "Betty came last.", zh: "貝蒂是最後一個來的。" },
  v0042: { en: "Just ask Tom.", zh: "問問湯姆吧。" },
  v0043: { en: "I need help.", zh: "我需要幫助。" },
  v0044: { en: "I feel cold.", zh: "我覺得冷。" },
  v0045: { en: "Gimme three.", zh: "給我來仨。" },
  v0046: { en: "I am the State!", zh: "朕即國家！" },
  v0047: { en: "I never lie.", zh: "我從不說謊。" },
  v0048: { en: "I can become angry.", zh: "我會生氣。" },
  v0049: { en: "Prices are high.", zh: "價格高。" },
  v0050: { en: "Do something!", zh: "做點什麼吧！" },
  v0051: { en: "It really works.", zh: "真的有用。" },
  v0052: { en: "Most people think so.", zh: "大部分的人是這麼想的。" },
  v0053: { en: "Get another chair.", zh: "再拿一把椅子。" },
  v0054: { en: "How much more?", zh: "還要多少？" },
  v0055: { en: "We're a family.", zh: "我們是個家庭。" },
  v0056: { en: "I own a horse.", zh: "我擁有一匹馬。" },
  v0057: { en: "Don't leave!", zh: "別走！" },
  v0058: { en: "Put it down.", zh: "放下。" },
  v0059: { en: "I'm not old.", zh: "我不老。" },
  v0060: { en: "What do you mean?", zh: "你是什麼意思？" },
  v0061: { en: "Keep trying.", zh: "繼續努力。" },
  v0062: { en: "I'm a student.", zh: "我是學生。" },
  v0063: { en: "Let me know.", zh: "讓我知道。" },
  v0064: { en: "That's great.", zh: "那真是太好了。" },
  v0065: { en: "It's all the same.", zh: "都一樣。" },
  v0066: { en: "What's your blood group?", zh: "你的血型是什麼？" },
  v0067: { en: "Let's begin.", zh: "讓我們開始吧。" },
  v0068: { en: "You seem busy.", zh: "你好像很忙。" },
  v0069: { en: "I love my country.", zh: "我愛我的祖國。" },
  v0070: { en: "I need help.", zh: "我需要幫助。" },
  v0071: { en: "Do you talk?", zh: "你說嗎?" },
  v0072: { en: "Turn it off.", zh: "把它關掉。" },
  v0073: { en: "No problem at all!", zh: "什麼問題都沒有！" },
  v0074: { en: "Let's start!", zh: "讓我們開始吧。" },
  v0075: { en: "Shake my hand.", zh: "和我握手。" },
  v0076: { en: "Show him in.", zh: "讓他進來。" },
  v0077: { en: "So take part!", zh: "快來參加吧！" },
  v0078: { en: "I like that place.", zh: "我喜歡那個地方。" },
  v0079: { en: "Buy a few apples.", zh: "買幾顆蘋果。" },
  v0080: { en: "The case is closed.", zh: "結案了。" },
  v0081: { en: "Until next week.", zh: "直到下週。" },
  v0082: { en: "You've got company.", zh: "你已經有人陪伴了。" },
  v0083: { en: "The system worked.", zh: "系統執行起來了。" },
  v0084: { en: "Is he right?", zh: "他對嗎？" },
  v0085: { en: "This program is a rerun.", zh: "這個節目是重播。" },
  v0086: { en: "I can hear it.", zh: "我聽得到。" },
  v0087: { en: "I play alone.", zh: "我獨自玩。" },
  v0088: { en: "Keep religion out of government.", zh: "別讓宗教影響政府。" },
  v0089: { en: "Run off now!", zh: "落跑吧！" },
  v0090: { en: "It's too small.", zh: "太小了。" },
  v0091: { en: "What's the number?", zh: "電話號碼是多少？" },
  v0092: { en: "I'm always busy.", zh: "我總是有事。" },
  v0093: { en: "I can't move.", zh: "我動不了。" },
  v0094: { en: "I'm a night owl.", zh: "我是個夜貓子。" },
  v0095: { en: "I live here.", zh: "我住在這。" },
  v0096: { en: "That's the point.", zh: "這正是問題的關鍵。" },
  v0097: { en: "I believe you.", zh: "我相信你。" },
  v0098: { en: "Can't hold it in.", zh: "俺不中嘞。" },
  v0099: { en: "Today was fun.", zh: "今天很有趣。" },
  v0100: { en: "Bring him in.", zh: "帶他進來。" },
  v0101: { en: "Accidents happen.", zh: "事故發生。" },
  v0102: { en: "Who is next?", zh: "下一個是誰？" },
  v0103: { en: "It left 60 million dead.", zh: "總共造成 6000 萬人死亡。" },
  v0104: { en: "I'm at home.", zh: "我在家。" },
  v0105: { en: "Drink water.", zh: "喝水。" },
  v0106: { en: "Clean the room.", zh: "打掃房間。" },
  v0107: { en: "Do you write?", zh: "你寫嗎?" },
  v0108: { en: "My dear mother.", zh: "我親愛的媽媽" },
  v0109: { en: "The area was quiet.", zh: "這地區很安靜。" },
  v0110: { en: "It was a national scandal.", zh: "這是一件全國性的醜聞。" },
  v0111: { en: "Money talks.", zh: "金錢萬能。" },
  v0112: { en: "I doubt his story.", zh: "我懷疑他的故事。" },
  v0113: { en: "He looks young.", zh: "他看起來很年輕。" },
  v0114: { en: "In fact she lied.", zh: "事實上，她撒慌了。" },
  v0115: { en: "What month is this?", zh: "這個月是幾月？" },
  v0116: { en: "We're very different.", zh: "我們很不一樣。" },
  v0117: { en: "That's a lot!", zh: "很多!" },
  v0118: { en: "Don't study.", zh: "你不要學習了。" },
  v0119: { en: "It is a book.", zh: "是一本書。" },
  v0120: { en: "My eye hurts.", zh: "我的眼睛疼。" },
  v0121: { en: "I give my word.", zh: "我保證。" },
  v0122: { en: "It's business.", zh: "公事公辦。" },
  v0123: { en: "You have four dogs.", zh: "你有四隻狗。" },
  v0124: { en: "This is a serious issue.", zh: "這個問題很嚴重。" },
  v0125: { en: "I'm on your side.", zh: "我支援你。" },
  v0126: { en: "She is kind.", zh: "她很好。" },
  v0127: { en: "My head aches.", zh: "我頭痛。" },
  v0128: { en: "So far, so good.", zh: "迄今，一切妥當。" },
  v0129: { en: "Is it black?", zh: "那是黑色的嗎？" },
  v0130: { en: "All day long.", zh: "一整天。" },
  v0131: { en: "Give me a little.", zh: "給我一點兒。" },
  v0132: { en: "My house is big.", zh: "我家很大。" },
  v0133: { en: "Cows provide us with milk.", zh: "奶牛為我們提供牛奶。" },
  v0134: { en: "The service here is awful.", zh: "這裡的服務很糟糕。" },
  v0135: { en: "I'm a friend.", zh: "我是朋友。" },
  v0136: { en: "It's not important.", zh: "這個不重要。" },
  v0137: { en: "He's my father.", zh: "他是我的爸爸。" },
  v0138: { en: "Sit beside me.", zh: "坐我旁邊。" },
  v0139: { en: "Take it away.", zh: "拿走。" },
  v0140: { en: "Knowledge is power.", zh: "知識就是力量。" },
  v0141: { en: "He left an hour ago.", zh: "他一小時前走了。" },
  v0142: { en: "What a game!", zh: "這遊戲太棒了！" },
  v0143: { en: "I often hiccup.", zh: "我經常打嗝。" },
  v0144: { en: "That's MY line!", zh: "那是我該說的話!" },
  v0145: { en: "I support political reform.", zh: "我支援政治改革。" },
  v0146: { en: "It's a dead end.", zh: "這是個死衚衕。" },
  v0147: { en: "Did you ever try?", zh: "你試過嗎？" },
  v0148: { en: "Stand aside.", zh: "一邊站著。" },
  v0149: { en: "It's my bad.", zh: "這是我的錯。" },
  v0150: { en: "I won't lose!", zh: "我不會輸！" },
  v0151: { en: "However, I have no money.", zh: "但是，我沒有錢。" },
  v0152: { en: "Every member must attend.", zh: "所有的成員都必須參加。" },
  v0153: { en: "Pay attention!", zh: "請注意！" },
  v0154: { en: "He is the law.", zh: "他就是王法。" },
  v0155: { en: "Meet me there.", zh: "在那裡見我。" },
  v0156: { en: "I have a car.", zh: "我有一輛車。" },
  v0157: { en: "I like your city.", zh: "我喜歡你們的城市。" },
  v0158: { en: "I almost won.", zh: "我幾乎贏了。" },
  v0159: { en: "The price does not include the box.", zh: "這個價格不包含這個箱子。" },
  v0160: { en: "We'll continue.", zh: "我們要繼續下去。" },
  v0161: { en: "Set me free!", zh: "釋放我！" },
  v0162: { en: "See you later!", zh: "再見！" },
  v0163: { en: "Tom is an activist in his community.", zh: "湯姆是社群中的積極分子。" },
  v0164: { en: "My name is 王明.", zh: "我叫王明。" },
  v0165: { en: "Give me five!", zh: "擊掌！" },
  v0166: { en: "Return at once.", zh: "馬上回來。" },
  v0167: { en: "Paper is white.", zh: "紙是白色的。" },
  v0168: { en: "I like math least of all.", zh: "我最不喜歡數學。" },
  v0169: { en: "He was elected president.", zh: "他被選為總統。" },
  v0170: { en: "Are you for real?", zh: "你是認真的嗎？" },
  v0171: { en: "Tom can change.", zh: "湯姆能改變。" },
  v0172: { en: "Our team lost, 2-0.", zh: "我們隊0:2輸了。" },
  v0173: { en: "Every minute counts.", zh: "分秒必爭。" },
  v0174: { en: "Do your best.", zh: "盡力而為。" },
  v0175: { en: "He came several times.", zh: "他來了很多次了。" },
  v0176: { en: "I've no idea.", zh: "我一無所知。" },
  v0177: { en: "Don't kid me!", zh: "不要耍我！" },
  v0178: { en: "Over my dead body.", zh: "除非我死了！" },
  v0179: { en: "Information is power.", zh: "資訊就是力量。" },
  v0180: { en: "Nothing new.", zh: "沒什麼新鮮事。" },
  v0181: { en: "I lead a busy life.", zh: "我有一個忙碌的生活。" },
  v0182: { en: "I'm a social worker.", zh: "我是個社會工作人員。" },
  v0183: { en: "I understand.", zh: "我明白了。" },
  v0184: { en: "Let's watch TV.", zh: "看電視吧。" },
  v0185: { en: "Work together.", zh: "一起工作。" },
  v0186: { en: "Do you follow?", zh: "懂了嗎？" },
  v0187: { en: "He's the new CEO from the parent company in France.", zh: "他是來自法國母公司的新任執行長。" },
  v0188: { en: "Can we stop?", zh: "我們能停下嗎？" },
  v0189: { en: "I lost face.", zh: "我丟臉了。" },
  v0190: { en: "Anything new?", zh: "有什麼新鮮事嗎？" },
  v0191: { en: "Small timers can also create history.", zh: "小人物同樣可以創造歷史。" },
  v0192: { en: "He made fun of me in public.", zh: "他在公共場合取笑了我。" },
  v0193: { en: "It's already 11.", zh: "已經是11點了。" },
  v0194: { en: "He can read.", zh: "他識字。" },
  v0195: { en: "We are on the same level.", zh: "我們不在一個水平上。" },
  v0196: { en: "Allow me to go.", zh: "請允許我去。" },
  v0197: { en: "Add a little milk.", zh: "加點牛奶。" },
  v0198: { en: "Lock the office.", zh: "把辦公室鎖上。" },
  v0199: { en: "You spend too much money.", zh: "你花太多錢了。" },
  v0200: { en: "Go next door.", zh: "去隔壁。" },
  v0201: { en: "To your health!", zh: "祝你健康！" },
  v0202: { en: "Art for art's sake.", zh: "為藝術而藝術。" },
  v0203: { en: "Are you sure?", zh: "你肯定嗎？" },
  v0204: { en: "Who likes war?", zh: "誰喜歡戰爭?" },
  v0205: { en: "I like history.", zh: "我喜歡歷史。" },
  v0206: { en: "I threw a party.", zh: "我舉辦了一場派對。" },
  v0207: { en: "Apples grow on trees.", zh: "蘋果長在樹上。" },
  v0208: { en: "The result was modest.", zh: "結果並不可觀。" },
  v0209: { en: "Open Sesame!", zh: "芝麻開門！" },
  v0210: { en: "Good morning!", zh: "早上好！" },
  v0211: { en: "Can you walk?", zh: "你能走嗎？" },
  v0212: { en: "What's the reason?", zh: "是什麼原因呢？" },
  v0213: { en: "The battery is low.", zh: "電池快沒電了。" },
  v0214: { en: "Did Tom win?", zh: "湯姆贏了嗎？" },
  v0215: { en: "He is absorbed in his research.", zh: "他專注於他的研究。" },
  v0216: { en: "I am a girl.", zh: "我是個女孩兒。" },
  v0217: { en: "I'm a nice guy.", zh: "我是好人。" },
  v0218: { en: "Tom is early.", zh: "湯姆還早。" },
  v0219: { en: "The food is cold.", zh: "食物是冷的。" },
  v0220: { en: "Wait a moment.", zh: "請稍等。" },
  v0221: { en: "Air is invisible.", zh: "空氣是無形的。" },
  v0222: { en: "Teacher Guan!", zh: "關老師！" },
  v0223: { en: "Don't force me!", zh: "別逼我！" },
  v0224: { en: "I accept the offer.", zh: "我接受了報價。" },
  v0225: { en: "That's enough.", zh: "夠了。" },
  v0226: { en: "Education starts at home.", zh: "教育從家庭開始。" },
  v0227: { en: "Remember that.", zh: "給我記住。" },
  v0228: { en: "My foot hurts.", zh: "我的腳痛。" },
  v0229: { en: "Give Tom a second.", zh: "給湯姆一點時間。" },
  v0230: { en: "Be a good boy.", zh: "做個討人喜歡的小朋友。" },
  v0231: { en: "Maybe tomorrow.", zh: "可能明天吧。" },
  v0232: { en: "I'm able to swim.", zh: "我會游泳。" },
  v0233: { en: "\"Age?\" \"16.\"", zh: "‘年齡’ ‘16歲’" },
  v0234: { en: "He had decided on a new policy.", zh: "他已經決定了新的政策。" },
  v0235: { en: "I know everything.", zh: "我什麼都知道。" },
  v0236: { en: "I love rock.", zh: "我愛搖滾。" },
  v0237: { en: "Learning is a gradual process.", zh: "學習是一個循序漸進的過程。" },
  v0238: { en: "I love music.", zh: "我愛音樂。" },
  v0240: { en: "We can consider that.", zh: "我們可以考慮。" },
  v0241: { en: "Kelly will appear on TV.", zh: "凱莉將在電視上出現。" },
  v0242: { en: "Actually, I was wrong.", zh: "實際上我錯了。" },
  v0243: { en: "I buy tapes.", zh: "我買磁帶。" },
  v0244: { en: "Mary is probably rich.", zh: "瑪麗應該有錢。" },
  v0245: { en: "Wait for me!", zh: "等等我。" },
  v0246: { en: "The market is big.", zh: "市場很大。" },
  v0247: { en: "He will die.", zh: "他會死。" },
  v0248: { en: "Send it airmail.", zh: "航空郵寄它。" },
  v0249: { en: "We expect to win.", zh: "我們看來會贏。" },
  v0250: { en: "It makes sense.", zh: "那樣說得通。" },
  v0251: { en: "Birds build nests.", zh: "鳥兒築巢。" },
  v0252: { en: "Let us stay.", zh: "讓我們留下。" },
  v0253: { en: "It's fall now.", zh: "現在是秋天。" },
  v0254: { en: "Tom has a plan.", zh: "湯姆有個計畫。" },
  v0255: { en: "I cut class.", zh: "我翹課了。" },
  v0256: { en: "I miss college.", zh: "我想念大學。" },
  v0257: { en: "My interest quickened.", zh: "我的興趣被激起來了。" },
  v0258: { en: "Yes, of course.", zh: "當然是的。" },
  v0259: { en: "Someone came.", zh: "有人來了。" },
  v0260: { en: "We learn by experience.", zh: "我們從經驗中學習。" },
  v0261: { en: "What's today's date?", zh: "今天幾號？" },
  v0262: { en: "Fruit generally rots soon.", zh: "水果一般不久就會腐爛。" },
  v0263: { en: "Sorry I'm late.", zh: "對不起，我遲到了。" },
  v0264: { en: "His company didn't survive the crisis.", zh: "他的公司沒有從危機中倖存。" },
  v0265: { en: "His work is now complete.", zh: "他的工作現在完成了。" },
  v0266: { en: "I want a fan.", zh: "我想買風扇。" },
  v0267: { en: "Stick it on later.", zh: "等一下再粘。" },
  v0268: { en: "How would you define \"happiness\"?", zh: "你怎麼定義“幸福”？" },
  v0269: { en: "He tires easily.", zh: "他很容易覺得累。" },
  v0270: { en: "He dug a hole.", zh: "他挖了一個洞。" },
  v0271: { en: "Hydrogen is the lightest element.", zh: "氫是最輕的元素。" },
  v0272: { en: "Can you tell me about your marital status?", zh: "能告訴我你的婚姻狀況嗎？" },
  v0273: { en: "I had a vision.", zh: "我有一個設想。" },
  v0274: { en: "That's normal.", zh: "很正常。" },
  v0275: { en: "I've never been on a ship.", zh: "我從來沒乘坐船。" },
  v0276: { en: "The stone is heavy.", zh: "這個石頭很重。" },
  v0277: { en: "There isn't any solution.", zh: "無解。" },
  v0278: { en: "Work slowly.", zh: "幹活慢點。" },
  v0279: { en: "Please put your baggage on this scale.", zh: "請把你的行李放在這秤上。" },
  v0280: { en: "Let me introduce it.", zh: "我介紹一下。" },
  v0281: { en: "He is a bad driver.", zh: "他是個糟糕的司機。" },
  v0282: { en: "Did Spot go, too?", zh: "Spot也去了嗎？" },
  v0283: { en: "We lack one spoon.", zh: "缺一把勺子。" },
  v0284: { en: "This is ice.", zh: "這是冰塊。" },
  v0285: { en: "Drink water.", zh: "喝水。" },
  v0286: { en: "The sun sets.", zh: "夕陽西下。" },
  v0287: { en: "I can't judge distance.", zh: "我無法判斷距離。" },
  v0288: { en: "Wood floats.", zh: "木頭會漂浮。" },
  v0289: { en: "What a big truck!", zh: "多麼大的一輛卡車啊！" },
  v0290: { en: "Let me handle this.", zh: "讓我來處理。" },
  v0291: { en: "Look at that mountain.", zh: "看那山！" },
  v0292: { en: "A recent survey shows that the number of smokers is decreasing.", zh: "最近的一項調查顯示吸菸的人數減少了。" },
  v0293: { en: "He was supposed to come.", zh: "他應該來的。" },
  v0294: { en: "This is a Turkish tradition.", zh: "這是個土耳其的傳統。" },
  v0295: { en: "I hate winter.", zh: "我恨冬天。" },
  v0296: { en: "She lives in a village.", zh: "她住在一個村子裡。" },
  v0297: { en: "They refuse to integrate.", zh: "她們拒絕融入。" },
  v0298: { en: "The sales are slipping.", zh: "銷售率正在急劇下滑。" },
  v0299: { en: "Do a barrel roll.", zh: "做個桶滾。" },
  v0300: { en: "English is a communication tool.", zh: "英語是溝通的工具。" },
  v0301: { en: "It's just a blip on a screen.", zh: "只是在螢幕上閃了一下。" },
  v0302: { en: "No pain no gain.", zh: "一分耕耘，一分收穫。" },
  v0304: { en: "I must hide.", zh: "我需要躲起來。" },
  v0305: { en: "Is that pure gold?", zh: "那是純金嗎？" },
  v0306: { en: "Welcome to the club.", zh: "歡迎來到俱樂部。" },
  v0307: { en: "He has a farm.", zh: "他有一個農場。" },
  v0308: { en: "She is full of potential.", zh: "她充滿潛力。" },
  v0309: { en: "Don't ever say this in my presence again!", zh: "別在我面前再提了！" },
  v0310: { en: "He is an independent thinker.", zh: "他是個獨立思考者。" },
  v0311: { en: "He's really in good shape.", zh: "他狀態真的很好。" },
  v0312: { en: "I am a slow reader.", zh: "我看書很慢的。" },
  v0313: { en: "The contract was signed.", zh: "契約簽訂了。" },
  v0314: { en: "The crowd is going nuts.", zh: "大家都快瘋了。" },
  v0315: { en: "Words express thoughts.", zh: "語言表達思想。" },
  v0316: { en: "God willing...", zh: "若天准許......" },
  v0317: { en: "I like the previous person.", zh: "喜歡上一個人。" },
  v0318: { en: "I play in a band.", zh: "我在一個樂團裡演奏。" },
  v0319: { en: "Obviously not!", zh: "當然不行！" },
  v0320: { en: "I own a horse.", zh: "我擁有一匹馬。" },
  v0321: { en: "I'm not interested.", zh: "我不感興趣。" },
  v0322: { en: "I aimed my gun at the target.", zh: "我把我的手槍指向了目標。" },
  v0323: { en: "I've been in prison.", zh: "我進過監獄。" },
  v0324: { en: "I'll ride with Tom.", zh: "我要和湯姆一起騎車。" },
  v0325: { en: "I stand guard.", zh: "我站崗。" },
  v0326: { en: "Tom is on good terms with John.", zh: "湯姆和約翰關係很好。" },
  v0327: { en: "You're a reporter.", zh: "你是個記者。" },
  v0328: { en: "The demand is huge.", zh: "好大一顆鑽。" },
  v0329: { en: "Do you deliver on Sundays?", zh: "你們週日送貨嗎？" },
  v0330: { en: "She sent a text.", zh: "她發了一條簡訊。" },
  v0331: { en: "I have a tool.", zh: "我有一個工具。" },
  v0332: { en: "Don't be so wild, Jack.", zh: "傑克,不要那麼撒野。" },
  v0333: { en: "Lightning struck the vehicle.", zh: "閃電擊中了車子。" },
  v0334: { en: "You must observe the law.", zh: "你必須遵守法律。" },
  v0335: { en: "Have a nice flight.", zh: "飛行愉快！" },
  v0337: { en: "Your work is below average.", zh: "你的工作表現低於平均水平。" },
  v0339: { en: "It is to his advantage.", zh: "這對他有利。" },
  v0340: { en: "Make it quick.", zh: "快點。" },
  v0341: { en: "Strong leadership was needed.", zh: "他們需要領導團隊。" },
  v0342: { en: "We work to earn money.", zh: "我們為了賺錢而工作。" },
  v0343: { en: "We bought a pound of tea.", zh: "我們買了一磅的茶。" },
  v0344: { en: "Your theory has no scientific basis.", zh: "你的理論並沒有科學根據。" },
  v0345: { en: "I like bright colors.", zh: "我喜歡明亮的顏色。" },
  v0346: { en: "The doctor decided to operate at once.", zh: "醫生決定立刻動手術。" },
  v0347: { en: "Be my guest.", zh: "做我的客人吧。" },
  v0348: { en: "The sample isn't pure enough.", zh: "樣本不夠純淨。" },
  v0349: { en: "I will work hard to contribute!", zh: "我將會努力作貢獻的！" },
  v0350: { en: "I learned to use a command block today.", zh: "我今天學會用命令方塊了。" },
  v0351: { en: "You need protection.", zh: "你需要保護。" },
  v0352: { en: "Fighting won't settle anything.", zh: "打架解決不了問題。" },
  v0353: { en: "I'll feed the dog.", zh: "我要餵狗。" },
  v0354: { en: "I collect stamps.", zh: "我收集郵票。" },
  v0355: { en: "We decided to stay an additional day.", zh: "我們決定多待一天。" },
  v0356: { en: "It is highly improper.", zh: "這實在不合適。" },
  v0357: { en: "We know the identity of Tom's killer.", zh: "我們知道湯姆的殺手是誰。" },
  v0358: { en: "It's a misleading title.", zh: "這是一個誤導性的標題。" },
  v0359: { en: "Lesson Two is easy.", zh: "第二課很簡單。" },
  v0360: { en: "I've lost faith in you.", zh: "我對你失去信心" },
  v0361: { en: "Is this a river?", zh: "這是一條河嗎?" },
  v0362: { en: "May I take a photo?", zh: "請問可以給您拍張照片嗎？" },
  v0364: { en: "Count me in.", zh: "算我一個." },
  v0365: { en: "Maybe tomorrow.", zh: "可能明天吧。" },
  v0366: { en: "Shougongsha is an old Chinese technique to test a woman's virginity.", zh: "守宮砂是中國古代用來驗證女人貞操的方法." },
  v0367: { en: "Follow his path.", zh: "跟隨他的道路。" },
  v0368: { en: "My ear is itching.", zh: "我耳朵癢。" },
  v0369: { en: "This is his shop.", zh: "這是他的店。" },
  v0371: { en: "Everyone will accept that idea in principle.", zh: "每個人都將在原則上同意那個想法。" },
  v0372: { en: "I cannot lift him.", zh: "我抱不起他。" },
  v0373: { en: "Tom can't cross the border.", zh: "Tom沒辦法穿過邊界。" },
  v0374: { en: "We won 6-2 in today's competition.", zh: "今天的比賽我們六比二贏了。" },
  v0375: { en: "Can you jump rope?", zh: "你能跳繩嗎？" },
  v0376: { en: "We gather here once a week.", zh: "我們每週在這兒聚一次。" },
  v0377: { en: "They've upped my limit.", zh: "他們提高了我的限額。" },
  v0378: { en: "Get fit fast.", zh: "速成好身材。" },
  v0379: { en: "I want to cry.", zh: "我想哭。" },
  v0380: { en: "Keep away from the electrical equipment.", zh: "遠離電器裝置。" },
  v0381: { en: "It's worth a go.", zh: "它值得一試。" },
  v0382: { en: "He's just a business associate.", zh: "他只是個事業合夥人。" },
  v0383: { en: "This famous mountain climber is a critic of mass tourism.", zh: "這位著名的登山家批評大眾旅遊。" },
  v0384: { en: "It's a warm day.", zh: "天氣暖和。" },
  v0385: { en: "Only some students understand that aspect.", zh: "只有幾個學生懂那個方面。" },
  v0386: { en: "They insist that he should go.", zh: "他們堅持讓他走。" },
  v0387: { en: "His failure is obvious.", zh: "他的失敗是顯而易見的。" },
  v0388: { en: "I don't know my father's annual income.", zh: "我不知到我爸的年收入是多少。" },
  v0389: { en: "This is my comment.", zh: "這是我的評論。" },
  v0390: { en: "Forget the sad affair.", zh: "把悲傷的事忘掉吧。" },
  v0391: { en: "I'm responsible for that.", zh: "我對此負有責任。" },
  v0392: { en: "Is his pulse regular?", zh: "他的脈搏正常嗎？" },
  v0393: { en: "That rumor soon spread.", zh: "那個謠言很快傳播開來。" },
  v0394: { en: "We elected him chairman.", zh: "我們選了他當主席。" },
  v0395: { en: "You like baseball?", zh: "你喜歡棒球嗎？" },
  v0396: { en: "That's soft.", zh: "這很軟。" },
  v0397: { en: "Ignore Tom and me.", zh: "無視湯姆和我。" },
  v0398: { en: "I have an egg.", zh: "我有一隻蛋。" },
  v0399: { en: "I have a firm belief in his innocence.", zh: "我堅信他是無辜的。" },
  v0400: { en: "Can you demonstrate it?", zh: "您可以示範一下嗎?" },
  v0401: { en: "Anybody home?", zh: "家裡有人嗎？" },
  v0402: { en: "Did you murder Tom?", zh: "是你殺了湯姆嗎？" },
  v0403: { en: "He accepted her gift.", zh: "他接受了她的禮物。" },
  v0404: { en: "Why is religion necessary?", zh: "為什麼宗教是必要的？" },
  v0405: { en: "Let's review.", zh: "咱們回顧一下。" },
  v0406: { en: "You don't want to be an editor?", zh: "你不想做編輯？" },
  v0408: { en: "I hate coffee.", zh: "我討厭咖啡。" },
  v0409: { en: "I signed the document.", zh: "我簽署了檔案。" },
  v0410: { en: "Full speed ahead!", zh: "全速前進！" },
  v0411: { en: "He's very cross.", zh: "他非常生氣。" },
  v0412: { en: "Don't drive under the influence of drink.", zh: "酒後別開車 。" },
  v0413: { en: "Thanks anyway.", zh: "還是要說謝謝的。" },
  v0414: { en: "She tried to commit suicide.", zh: "她企圖自殺。" },
  v0415: { en: "Did Tom ever threaten you?", zh: "湯姆威脅過你嗎？" },
  v0416: { en: "I have a female cow.", zh: "我有一頭母牛。" },
  v0417: { en: "Youth is an asset.", zh: "年輕就是本錢。" },
  v0418: { en: "A cold wave of fear hit me like a brick.", zh: "一陣寒意像磚頭一樣擊中了我。" },
  v0419: { en: "He's afraid.", zh: "他害怕。" },
  v0420: { en: "It's quarter to seven.", zh: "六點四十五了。" },
  v0421: { en: "Tom has a veterinary background.", zh: "Tom有獸醫背景。" },
  v0422: { en: "Tom is a Boston native.", zh: "湯姆是波士頓本地人。" },
  v0423: { en: "Tom has very broad shoulders.", zh: "湯姆肩膀很寬。" },
  v0424: { en: "Ah, wonderful.", zh: "啊，真棒！" },
  v0425: { en: "I can't deny it.", zh: "我無法否認。" },
  v0426: { en: "Tom has apparently done that already.", zh: "很明顯，湯姆已經做完了。" },
  v0427: { en: "I opened the window slightly.", zh: "我開了點窗戶。" },
  v0428: { en: "Let's see what the reaction is.", zh: "看看反應如何。" },
  v0429: { en: "Tom kicked me twice.", zh: "湯姆踢了我兩下。" },
  v0430: { en: "Suit yourself.", zh: "隨你開心。" },
  v0432: { en: "The tree stopped growing.", zh: "這棵樹停止生長了。" },
  v0433: { en: "Blow your nose.", zh: "擤擤你的鼻子。" },
  v0434: { en: "The road is under construction.", zh: "路正在建。" },
  v0435: { en: "AI means Artificial Intelligence.", zh: "AI是人工智慧的略稱。" },
  v0436: { en: "Destroy this temple.", zh: "摧毀這個寺廟。" },
  v0437: { en: "I am a cook.", zh: "我是一名廚師。" },
  v0438: { en: "We have a special connection.", zh: "我們有特殊聯絡。" },
  v0439: { en: "Plastic does not burn easily.", zh: "塑膠不易燃燒。" },
  v0440: { en: "Wait a second. My shoe is untied.", zh: "等下，我鞋帶散了。" },
  v0441: { en: "He is my neighbor.", zh: "他是我鄰居。" },
  v0442: { en: "What grade are you in?", zh: "你幾年級？" },
  v0443: { en: "No context, no text.", zh: "沒有上下文就沒有詞義。" },
  v0444: { en: "Are you on the committee?", zh: "你是委員會中的成員嗎？" },
  v0445: { en: "I made a mistake.", zh: "我搞錯了。" },
  v0446: { en: "What's their location?", zh: "他們的位置是？" },
  v0447: { en: "Tom changed clothes.", zh: "湯姆換了衣服。" },
  v0448: { en: "She is quiet.", zh: "她很安靜。" },
  v0449: { en: "Dress quickly.", zh: "快點穿。" },
  v0450: { en: "You promise?", zh: "你保證？" },
  v0451: { en: "Be more aware!", zh: "留點兒神！" },
  v0452: { en: "The function f vanishes on the set X.", zh: "函式 f 在集合 X 上為零。" },
  v0453: { en: "She is all skin and bone.", zh: "她瘦得只剩皮包骨了。" },
  v0454: { en: "Tom is more active.", zh: "湯姆更活躍。" },
  v0455: { en: "Our branches extend all over the country.", zh: "我們的分店佈滿全國。" },
  v0456: { en: "Hello, Chief!", zh: "首長好！" },
  v0457: { en: "We may combine your personal information with other information.", zh: "我們可能會將你的私人資訊和其他資訊結合在一起。" },
  v0458: { en: "I have wine.", zh: "我有酒。" },
  v0459: { en: "It's cool today.", zh: "今天很涼快。" },
  v0461: { en: "Let's go by bus.", zh: "讓我們坐公共汽車去。" },
  v0462: { en: "I was learning.", zh: "我在學習。" },
  v0463: { en: "Welcome to hell!", zh: "歡迎來到地獄。" },
  v0464: { en: "It's dangerous!", zh: "它是危險的!" },
  v0465: { en: "I'll remind you.", zh: "我會提醒你的。" },
  v0466: { en: "He lived a moral life.", zh: "他以君子之道生活。" },
  v0467: { en: "He is from the United States.", zh: "他來自美國。" },
  v0468: { en: "She speaks relatively fast.", zh: "她說話相當快。" },
  v0469: { en: "This is your victory.", zh: "這是你們的勝利。" },
  v0470: { en: "Academic fraud is more common than you might think.", zh: "學術造假比你想像的普遍。" },
  v0471: { en: "I'm healthy.", zh: "我身體很好。" },
  v0472: { en: "Let go of your negative outlook on life.", zh: "請拋開你那些負面的人生觀。" },
  v0473: { en: "Are you following me?", zh: "你在跟著我嗎？" },
  v0474: { en: "This is a city of real historical value.", zh: "這是一個具有歷史價值的城市。" },
  v0475: { en: "Drink the medicine.", zh: "喝藥了。" },
  v0476: { en: "Would you like a tour?", zh: "你想參觀一下嗎？" },
  v0477: { en: "We depend on you.", zh: "我們可全指望你了。" },
  v0478: { en: "Grab the thief!", zh: "抓賊啊！" },
  v0479: { en: "Is this the direct way to the Prado?", zh: "這條路是不是直接通往普拉多博物館？" },
  v0480: { en: "The classroom is clean.", zh: "教室很乾淨。" },
  v0481: { en: "Please contact us.", zh: "請聯絡我們。" },
  v0482: { en: "He wants justice.", zh: "他想要正義。" },
  v0483: { en: "Participate!", zh: "參與！" },
  v0484: { en: "He shaves daily.", zh: "他每天刮鬍子。" },
  v0485: { en: "That's not fair.", zh: "那是不公平的。" },
  v0486: { en: "I have a pair of shoes.", zh: "我有一雙鞋。" },
  v0487: { en: "I'm not famous.", zh: "我沒名氣。" },
  v0488: { en: "Exercise outdoors.", zh: "戶外運動。" },
  v0489: { en: "My knee aches.", zh: "我的膝蓋疼。" },
  v0490: { en: "Is this a flower?", zh: "這是花嗎？" },
  v0491: { en: "Why should I hire Tom?", zh: "為什麼我要僱傭Tom？" },
  v0492: { en: "They look familiar.", zh: "他們很眼熟。" },
  v0493: { en: "Local people can give appropriate advice.", zh: "當地人可以給予適切的建議。" },
  v0494: { en: "Printing ink is in short supply.", zh: "油墨快沒了。" },
  v0495: { en: "My house is fully insured.", zh: "我的房子絕對保險。" },
  v0496: { en: "Is Tom an actor?", zh: "湯姆是演員嗎？" },
  v0497: { en: "She just gave birth.", zh: "她剛生了孩子。" },
  v0498: { en: "Search by name.", zh: "以姓名搜尋。" },
  v0499: { en: "What's democracy?", zh: "什麼是民主？" },
  v0501: { en: "My primary concern is your safety.", zh: "我最關心的是你的安全。" },
  v0502: { en: "He died yesterday.", zh: "他昨天死了。" },
  v0503: { en: "Draw a circle.", zh: "畫一個圈。" },
  v0504: { en: "This is an old device.", zh: "這是臺舊裝置。" },
  v0505: { en: "In Progress.", zh: "進行中。" },
  v0506: { en: "Yanni hit rock bottom.", zh: "燕妮跌到谷底。" },
  v0507: { en: "Free Turtle Island!", zh: "解放龜島！" },
  v0508: { en: "What is the exchange rate?", zh: "匯率是多少？" },
  v0509: { en: "Tom is clean.", zh: "湯姆是乾淨的。" },
  v0512: { en: "The train is in.", zh: "這班火車已經到了。" },
  v0513: { en: "He saluted the lady.", zh: "他向那位女士問好。" },
  v0514: { en: "Minghui is my colleague.", zh: "明惠是我的同事。" },
  v0515: { en: "This application is awesome.", zh: "這個應用好極了。" },
  v0516: { en: "Don't lean against the wall.", zh: "別倚著牆。" },
  v0517: { en: "My neck hurts.", zh: "我脖子痛。" },
  v0518: { en: "The damage is done.", zh: "覆水難收。" },
  v0519: { en: "That's plastic.", zh: "那是塑膠。" },
  v0520: { en: "She is tall.", zh: "她高。" },
  v0521: { en: "Cancer is a great enemy of humanity.", zh: "癌症是人類的大敵。" },
  v0522: { en: "Correlation does not imply causation.", zh: "相關關係不導致因果關係。" },
  v0524: { en: "You're reliable.", zh: "你很可靠。" },
  v0525: { en: "I want beef, too.", zh: "\"我也要牛肉。\"" },
  v0526: { en: "Meg is filled with excitement.", zh: "麥格激動不已。" },
  v0527: { en: "I call architecture frozen music.", zh: "我將建築稱作被凍結的音樂。" },
  v0528: { en: "Who is the Administrative Assistant?", zh: "誰是行政助理？" },
  v0529: { en: "I have occasional pains in the stomach.", zh: "我的胃偶爾會陣痛。" },
  v0530: { en: "My elbow still hurts.", zh: "我的手肘還在痛。" },
  v0531: { en: "To him this is a deadly blow.", zh: "這對他來說是致命的打擊。" },
  v0533: { en: "Never confuse pity with love.", zh: "同情心和愛心絕不可混為一談。" },
  v0534: { en: "Look! An airplane!", zh: "看！飛機！" },
  v0535: { en: "Attached is my monthly report.", zh: "附上我這個月的報告。" },
  v0536: { en: "It looks like a duck.", zh: "它看起來像一隻鴨子。" },
  v0540: { en: "Give a lecture on literature.", zh: "做一次文學講座。" },
  v0541: { en: "The sixth prime minister of Malaysia is Dato' Sri Najib Abdul Razak.", zh: "馬來西亞第六任首相是拿督斯利納吉·阿都拉薩。" },
  v0543: { en: "Tom made a sandwich.", zh: "湯姆做了個三明治。" },
  v0545: { en: "Helen and Kathy rented an apartment in a suburb of Tokyo.", zh: "海倫和凱蒂在東京郊區租了個套間。" },
  v0546: { en: "I love the trunk.", zh: "我愛樹幹。" },
  v0548: { en: "A swallow flies very swiftly.", zh: "燕子飛得非常快。" },
  v0551: { en: "It's a trap!", zh: "這是一個陷阱！" },
  v0553: { en: "This cloth irons well.", zh: "這塊布料被熨得很好。" },
  v0557: { en: "I'm looking for my contact lens.", zh: "我在找我的隱形眼鏡。" },
  v0559: { en: "Lend it to him.", zh: "借給他." },
  v0560: { en: "I'm just a plain office worker.", zh: "我只是一個普通的上班族。" },
  v0561: { en: "Tom is a tax inspector.", zh: "湯姆是稅務督察。" },
  v0562: { en: "Academic fraud is more common than you might think.", zh: "學術造假比你想像的普遍。" },
  v0564: { en: "Tom's strict.", zh: "湯姆很嚴格。" },
  v0566: { en: "Frankly speaking, he's wrong.", zh: "坦率地說，他錯了。" },
  v0567: { en: "I broke a nail.", zh: "我的指甲斷了。" },
  v0568: { en: "The cat ate the rat.", zh: "貓吃了老鼠。" },
  v0569: { en: "The hallway needs to be wide enough for a wheelchair.", zh: "走廊要夠輪椅寬。" },
  v0570: { en: "Tom burst into tears.", zh: "湯姆淚流滿面。" },
  v0571: { en: "War is not inevitable.", zh: "戰爭並非不可避免。" },
  v0572: { en: "We got lost in the cave.", zh: "我們在山洞裡迷了路。" },
  v0574: { en: "There's a monster under my bed.", zh: "我的床下有怪獸。" },
  v0575: { en: "That is rather unexpected.", zh: "這真是很意外。" },
  v0577: { en: "He can overcome any obstacle.", zh: "他能夠超越所有困難。" },
  v0580: { en: "The herb used in that pasta sauce might be parsley.", zh: "用於那個義大利醬的香草可能是荷蘭芹。" },
  v0583: { en: "The unemployment rate went up to 5% because of the recession.", zh: "經濟不景氣失業率上升到了5％。" },
  v0584: { en: "What was his motive for doing it?", zh: "他那樣做有甚麼動機？" },
  v0585: { en: "This beer is bitter.", zh: "這種啤酒有苦味。" },
  v0586: { en: "Tom has written to me.", zh: "湯姆給我寫信了。" },
  v0587: { en: "The flood caused a lot of damage.", zh: "洪水造成了很大的損害。" },
  v0588: { en: "My pen is new.", zh: "我的鋼筆是新的。" },
  v0589: { en: "Management of a company is different from ownership of a company.", zh: "管理一間公司和擁有一間公司是不能相提並論的兩回事。" },
  v0590: { en: "I had a nightmare.", zh: "我做噩夢了。" },
  v0591: { en: "Korea allowed an inspection by the IAEA.", zh: "韓國允許了國際原子能總署的視察。" },
  v0594: { en: "You should consult your doctor.", zh: "你應該諮詢你的醫生。" },
  v0595: { en: "The ball is that boy's prized possession.", zh: "這個球是那個男孩的寶貝。" },
  v0597: { en: "Forgive her.", zh: "原諒她。" },
  v0599: { en: "The basement was flooded.", zh: "地下室被水淹了。" },
  v0600: { en: "Many people drift through life without a purpose.", zh: "許多人毫無目的地隨波逐流。" },
  v0602: { en: "Mark your maximum efforts.", zh: "盡力而為。" },
  v0606: { en: "The warrior is conscious of both his strength and his weakness.", zh: "戰士知道自己的力量和弱點。" },
  v0607: { en: "My prediction was accurate.", zh: "我的預言是真確的。" },
  v0608: { en: "Please hurry.", zh: "請抓緊時間。" },
  v0609: { en: "Don't step in the mud.", zh: "別走進泥地。" },
  v0610: { en: "A cell phone is as contaminated with bacteria as a toilet is.", zh: "手機如同馬桶一樣被細菌汙染。" },
  v0611: { en: "It's a privilege to meet you.", zh: "幸會。" },
  v0613: { en: "Children like outdoor activities.", zh: "孩子們喜歡戶外活動。" },
  v0614: { en: "Destroy this temple.", zh: "摧毀這個寺廟。" },
  v0615: { en: "We broadcast news on the hour.", zh: "我們正點播報新聞。" },
  v0616: { en: "Suck my dick.", zh: "吸我的雞巴。" },
  v0617: { en: "You are random.", zh: "你隨意。" },
  v0618: { en: "The curtain fell.", zh: "謝幕了。" },
  v0619: { en: "Tom sprained his wrist.", zh: "湯姆扭傷了手腕。" },
  v0620: { en: "The pond is 3 meters deep.", zh: "這個池塘有三米深。" },
  v0622: { en: "He admitted his guilt.", zh: "他承認他有罪。" },
  v0623: { en: "Look after the cattle.", zh: "照顧好那些牛！" },
  v0624: { en: "That's weird.", zh: "奇怪。" },
  v0625: { en: "What is the minimum wage in Georgia?", zh: "請問喬治亞洲的最低工資是多少？" },
  v0626: { en: "She is walking.", zh: "她在行走。" },
  v0628: { en: "I have to take a dump.", zh: "我要拉屎。" },
  v0629: { en: "The kilt is not a skirt.", zh: "蘇格蘭短褶裙不是裙子。" },
  v0631: { en: "It's very uncomfortable.", zh: "真讓人不舒服。" },
  v0633: { en: "This is the ideology to which my speech is written.", zh: "我的演講稿就是依據這個理論寫的。" },
  v0634: { en: "Play us a tune.", zh: "給我們彈一手。" },
  v0635: { en: "I will play Sudoku then instead of continuing to bother you.", zh: "那我就不繼續打擾你，玩數獨遊戲去了。" },
  v0636: { en: "Is that the railroad station?", zh: "這是火車站嗎？" },
  v0637: { en: "Can she endure a long trip?", zh: "她能忍受長途旅行嗎？" },
  v0638: { en: "I don't wish to harm you.", zh: "我不想傷害你。" },
  v0639: { en: "The ozone in the stratosphere absorbs ultraviolet radiation.", zh: "平流層的臭氧會吸收紫外線。" },
  v0640: { en: "This may sound like blowing my own horn, but ...", zh: "這聽起來可能像是我在自吹自擂, 但是..." },
  v0642: { en: "Country life is very peaceful in comparison with city life.", zh: "和都市生活相比，鄉村生活和諧多了。" },
  v0643: { en: "History develops through the replacement of the old by the new.", zh: "新事物取代舊事物推動歷史發展。" },
  v0645: { en: "I want a guitar.", zh: "我想要一把吉他。" },
  v0646: { en: "The rope broke under the strain.", zh: "繩子被拉斷了。" },
  v0647: { en: "Behave yourself.", zh: "規矩點。" },
  v0650: { en: "Aoi became a dancer.", zh: "葵成為一個舞蹈家。" },
  v0651: { en: "May I use your ink pad?", zh: "可以借你的印臺一用嗎？" },
  v0652: { en: "Can you drive a manual transmission?", zh: "你會開手排車嗎?" },
  v0653: { en: "Tom put the gun to his own head and pulled the trigger.", zh: "湯姆把槍頂到了自己頭上，扣動了扳機。" },
  v0655: { en: "I await updates.", zh: "我等待更新。" },
  v0656: { en: "I'm retired.", zh: "我退休了。" },
  v0657: { en: "What did you spill?", zh: "你灑了什麼？" },
  v0658: { en: "I'm truly grateful!", zh: "真是太感謝你了！" },
  v0659: { en: "Kenya used to be a British colony.", zh: "肯亞曾經是英國的殖民地。" },
  v0662: { en: "This plant is indigenous to Canada.", zh: "這種植物原產於加拿大。" },
  v0663: { en: "He closed his eyes.", zh: "他閉上了眼睛。" },
  v0664: { en: "I need a towel.", zh: "我需要一塊毛巾。" },
  v0666: { en: "We want to modify the regulations of our school.", zh: "我們想修改學校的規章制度。" },
  v0667: { en: "I've won first prize!", zh: "我贏得了第一名！" },
  v0668: { en: "The plane made a perfect landing.", zh: "這架飛機完美的著陸了。" },
  v0670: { en: "Is that a bat?", zh: "那是隻蝙蝠嗎？" },
  v0671: { en: "The fire alarm rang.", zh: "火警警報響了。" },
  v0672: { en: "I'm losing my grip.", zh: "我失去了控制。" },
  v0673: { en: "Happy Moon Festival!", zh: "中秋節快樂。" },
  v0674: { en: "He began to sweat.", zh: "他開始出汗了。" },
  v0675: { en: "Have you ever been to outer space?", zh: "你去過外層空間嗎？" },
  v0677: { en: "He is drunk.", zh: "他醉了。" },
  v0678: { en: "One day apart seems like a separation of three years.", zh: "一日不見如隔三秋。" },
  v0681: { en: "He studies French and web design.", zh: "他又學法語，又學怎麼做網站。" },
  v0683: { en: "Tom is intelligent.", zh: "湯姆很聰明。" },
  v0684: { en: "The USA is a republic.", zh: "美國是一個共和國。" },
  v0685: { en: "Sit wherever you like.", zh: "你愛坐哪裡就坐哪裡。" },
  v0686: { en: "To govern a country is no easy job.", zh: "統治一個國家不是一個簡單活。" },
  v0687: { en: "It's driving me crazy.", zh: "快把我逼瘋了" },
  v0689: { en: "We almost had Tom convinced.", zh: "我們差不多說服Tom了。" },
  v0690: { en: "Oranges are rich in vitamin C.", zh: "香橙含有豐富的維他命 C。" },
  v0691: { en: "Enthusiasm is contagious.", zh: "熱情具有傳染性。" },
  v0692: { en: "The motel can accommodate as many as 400 guests.", zh: "汽車旅館可以接待多達400名客人。" },
  v0693: { en: "Praise the Lord!", zh: "讚美主。" },
  v0694: { en: "The universe is endless.", zh: "宇宙無窮無盡。" },
  v0697: { en: "The world is in chaos.", zh: "世界處於混沌之中。" },
  v0699: { en: "I got a piece of lead for my mechanical pencil from her.", zh: "我從她那裡拿了一根自動鉛筆芯。" },
  v0702: { en: "He is past forty.", zh: "他已經超過四十歲了。" },
  v0703: { en: "Tom wrote a very profound report.", zh: "湯姆寫了篇非常有深度的報道。" },
  v0704: { en: "I have a friend waiting for me in the lobby.", zh: "有個朋友正在大堂等我。" },
  v0706: { en: "What is the currency of Taiwan?", zh: "臺灣的貨幣是什麼 ?" },
  v0707: { en: "He'll apologize.", zh: "他會道歉的。" },
  v0708: { en: "I want to reserve a room.", zh: "我想預定一個房間。" },
  v0709: { en: "I'm checking for laser beam alarm triggers.", zh: "我在檢查這裡有沒有雷射警報裝置。" },
  v0714: { en: "I believe it is a genuine Picasso.", zh: "我認為是一幅畢加索的原畫。" },
  v0715: { en: "My grandmother has a green thumb.", zh: "我祖母是個園藝巧手。" },
  v0716: { en: "Unity, justice and freedom are the pledge of fortune.", zh: "團結、公正和自由是幸福的保證。" },
  v0717: { en: "How horrible!", zh: "真糟糕！" },
  v0718: { en: "Can we effect a compromise?", zh: "我們不如各退一步吧。" },
  v0722: { en: "Don't scatter your things about.", zh: "不要把你的東西四處亂放。" },
  v0723: { en: "Women commonly live longer than men.", zh: "女性通常比男性長壽。" },
  v0724: { en: "Wires are used to convey electricity.", zh: "電線被用來運送電力。" },
  v0725: { en: "He's contemplating the complexity of contemporary life.", zh: "他思考著現代生活的複雜性。" },
  v0726: { en: "I'd like a fork.", zh: "我想要一把叉子。" },
  v0727: { en: "Don't twist my words.", zh: "不要扭曲我說的話。" },
  v0728: { en: "I've formatted your hard disk by mistake.", zh: "我不小心格式化了你的硬碟。" },
  v0729: { en: "I have a suspicion about his death.", zh: "我覺得他的死有點可疑。" },
  v0730: { en: "How do you relieve stress?", zh: "你怎麼釋放壓力？" },
  v0732: { en: "What a shame!", zh: "真丟人！" },
  v0733: { en: "She gave me a meaningful look.", zh: "她意味深長地看了我一眼。" },
  v0734: { en: "Tom is sweeping the sidewalk.", zh: "湯姆正在清掃人行道。" },
  v0736: { en: "Have a pleasant trip.", zh: "祝你一路上玩得愉快。" },
  v0737: { en: "This letter has no signature.", zh: "這封信沒署名。" },
  v0738: { en: "Suspend the game.", zh: "禁止遊戲。" },
  v0739: { en: "Who doesn't love a rebel?", zh: "誰不喜歡反叛者呢？" },
  v0740: { en: "Tom found a wonderful spouse in Mary.", zh: "湯姆認識了瑪莉這麼個好老婆。" },
  v0741: { en: "It's frozen hard.", zh: "真的很冰冷。" },
  v0742: { en: "A proper test does not allow the use of correction fluid.", zh: "正規的考試不允許使用塗改液。" },
  v0743: { en: "I asked the company for his resume.", zh: "我向他公司詢問了他的經歷。" },
  v0744: { en: "The Greeks invented a theoretical model of geometry.", zh: "希臘人建立了幾何學的理論模型。" },
  v0745: { en: "Sodium bicarbonate is commonly known as baking soda.", zh: "碳酸氫鈉通常被稱為小蘇打。" },
  v0746: { en: "People over 65 can receive a pension from the government.", zh: "過65歲的人就可以從政府那裡領退休金了。" },
  v0747: { en: "He got a promotion.", zh: "他升職了。" },
  v0748: { en: "That's a delicate matter.", zh: "那是個微妙的局勢。" },
  v0749: { en: "Come feel my forehead.", zh: "讓我摸摸你的額頭。" },
  v0750: { en: "Tom is an electrical engineer.", zh: "湯姆是一個電子工程師。" },
  v0751: { en: "Can Tebboune rebuild Algeria?", zh: "特布恩能重建阿爾及利亞嗎？" },
  v0752: { en: "Let me off the hook.", zh: "放過我吧。" },
  v0753: { en: "You'll bounce back.", zh: "你會東山再起的。" },
  v0754: { en: "I'm a detective.", zh: "我是個偵探。" },
  v0755: { en: "Did you hear the click?", zh: "你聽到了點選聲嗎？" },
  v0756: { en: "The traveler was delighted at the sight of a light in the distance.", zh: "發現了遠處的燈光的旅行者歡喜不已。" },
  v0758: { en: "Here is the exit!", zh: "出口在這裡！" },
  v0760: { en: "The coral reef is the region's prime attraction.", zh: "珊瑚礁是這個地區的主要景點。" },
  v0761: { en: "That isn't altogether false.", zh: "那不全是錯的。" },
  v0764: { en: "She's handy with a needle.", zh: "她擅長針線活。" },
  v0765: { en: "I hit him in the belly.", zh: "我打了他的肚子。" },
  v0766: { en: "Wolves scare me.", zh: "狼嚇到了我。" },
  v0767: { en: "Nice timing.", zh: "好時機。" },
  v0769: { en: "How long does it take for the airport shuttle to get to the airport?", zh: "穿梭班車到機場需要多長時間？" },
  v0770: { en: "Air is invisible.", zh: "空氣是無形的。" },
  v0772: { en: "Tom sprained his ankle.", zh: "湯姆崴了他的腳。" },
  v0773: { en: "He came to my rescue.", zh: "他拯救了我。" },
  v0776: { en: "We had a mild winter last year.", zh: "去年冬天很暖和。" },
  v0777: { en: "It is just noon.", zh: "現在才中午。" },
  v0778: { en: "He is identical to his older brother.", zh: "他跟哥哥一模一樣。" },
  v0779: { en: "I made Ann a doll.", zh: "我做了一個洋娃娃給安。" },
};
